### ISSUE TITLE
主力艦のソート順にidを追加する

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#100]
初期艦がLv150になったらそれ出したいしね

**Comment by b-wind** [comment]
Issue No 100 !!

**Comment by ponkotuy** [comment]
ここキリ番掲示板じゃないから！w

**Comment by ponkotuy** [comment]
とてもindex効き辛そうだけど、まぁmemberIdで絞ってるしMax200件ぐらいだし良いじゃろ https://github.com/ponkotuy/MyFleetGirls/commit/bbaf2d0e7b18ec9bc52b12ee53e788f06663bf34

**Comment by b-wind** [comment]
既存のクエリで INDEX 利いてるならそれを一次テーブル上で並べ替えるだけだからあんまり気にするほどでは無いかな。

ただ、類似の件として基本的にソート順が確定しない処理というのは止めた方が良いとは思う。
表示される物が不定であるというのは見ていて戸惑うしバグかどうか判断付かなくなるし。
DB でのソートか、プログラムでのソートかは問わないし 特に意味自体は無くて良いけど同じ条件下では同じものが出る方が好ましい。

**Comment by ponkotuy** [comment]
確かにその通りだと思う。初期のコードは割とそういうの多い。PRお待ちしております
