### ISSUE TITLE
改修資材再構成

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#107]
created忘れるとか、あんまりにも仕様が酷いので、一旦作りなおす

追加するデータ

- [x] created
- [x] 資材数
- [x] 明石改修の有無
- [x] 2番艦

**Comment by ponkotuy** [comment]
資材数は別テーブルでmasterとして持つことにしよう

**Comment by b-wind** [comment]
明石改修の有無 ってなに？

**Comment by ponkotuy** [comment]
明石と明石改で結果が違う可能性があると

**Comment by b-wind** [comment]
成功率が違う事は明言されてるね。明石改二や明石の姉妹艦が出る事も考慮して単純に旗艦保っておいた方が良いのでは。

**Comment by ponkotuy** [comment]
元々そのつもりでしたw

**Comment by ponkotuy** [comment]
これ忘れていた

- [ ] 元装備のRank

エエエエエ無いのおおお！？って感じだったよね

**Comment by ponkotuy** [comment]
Branch作った https://github.com/ponkotuy/MyFleetGirls/tree/refine_remodel

**Comment by ponkotuy** [comment]
資材数とテストがまだ（ネジが2つしかなくてな

**Comment by ponkotuy** [comment]
資材数を保存するmasterはできたが、この際に正確なslotitemの情報が必要で、追加修正を必要とする。
ProxyからはslotitemIdしか分からないので、このIDからサーバの情報でlevelを補完する必要があるのだが、現行改修時にupdateしないので、連続で改修したとき（またこれはとても良くありそうなことである）、古いlevelデータのまま間違ったmasterを生成する

**Comment by ponkotuy** [comment]
残タスク
- [ ] 装備変更時（特に改修時と開発時）にslotitemへの反映を行う
- [ ] 履歴Viewに資材数を表示する
- [ ] 実環境テスト

**Comment by ponkotuy** [comment]
テスト面倒過ぎて死ねるので実データでテストする（死亡フラグ
