### ISSUE TITLE
スナップショット ページから嫁艦設定が反映されない

### ISSUE THREAD

**Issue by b-wind** [ponkotuy/MyFleetGirls#110]
スナップショットページから任意に艦娘名を選択し、モーダルを開く。
https://myfleet.moe/user/636242/snapshot#modal=true&id=3422

「嫁艦に設定する」ボタンが表示され、押下で嫁艦設定画面に遷移するが
決定後も ユーザートップの嫁艦表示に反映されない。

**Comment by ponkotuy** [comment]
そもそも存在するかしないか分からない艦に嫁艦設定をするのがナンセンスなので、単にコピペミス。削除します

**Comment by ponkotuy** [comment]
コピーどころか共通だ。ビット立てて挙動変えるか

**Comment by b-wind** [comment]
羅針盤ページでは同様のリンクはあるが艦娘ページに遷移してからモーダルを表示するようになっている。
同じように処理して、艦娘ページの方で対象の存在チェックを行えば良いのでは無いか。

**Comment by ponkotuy** [comment]
むり。スナップショットの鑑娘は別データ

**Comment by b-wind** [comment]
そんなところとは思ったけれど、どちらかというとなぜ羅針盤ページは別データもしくはリンクにしない等の対応で無いのかは疑問に思った。

**Comment by ponkotuy** [comment]
羅針盤は鑑娘のデータを別にするべきなのにしなかったという点で残念実装。shipはロストがありうるから別で取っておくべきだった。Snapshotはその反省を踏まえて全て記録を残しているので完全に別物

**Comment by ponkotuy** [comment]
色々間違ってたし纏めて修正
https://github.com/ponkotuy/MyFleetGirls/commit/291192acfc330342486b2f00f17d5e7c29294138
