### ISSUE TITLE
イベント海域の表記が生データでは分かりにくいので名称を付けよう

### ISSUE THREAD

**Issue by b-wind** [ponkotuy/MyFleetGirls#114]
現状海域表記は基本生データで表示されており、通常海域は通称と一致しているため問題無いが
イベント海域のデータは分かりずらい。

例）29-1 -> ’15 冬イベ（２月）E-1 海域

表記の置き換えによって分かりやすくして欲しい。

**Comment by b-wind** [comment]
表記の置き換え案
| 生データ | 羅針盤・海戦 での表記 | 提督名下「攻略中」表記での正式名称 |
|-----------:|:------------|:------------|
|29-1|'15 冬 E-1| 迎撃！「トラック泊地強襲」 泊地周辺の敵潜を叩け！ |
|29-2|'15 冬 E-2||
|29-3|'15 冬 E-3||
|29-4|'15 冬 E-4||
|29-5|'15 冬 E-5||

**Comment by ponkotuy** [comment]
AreaIdの29を置き換える形での実装を考えているので、多分

> '15 冬 E'

とかで良いです。正式名称は必要ですか？

**Comment by b-wind** [comment]
AreaId のみの置き換えはうーん、個人的には個々の「海域名」としてみてるので想定外だったけど、
結果的には大差ないのでそれで良いかと。

正式名称は、モチベというかテンションの問題。有った方がやる気出るとかそういう事。

**Comment by ponkotuy** [comment]
とりあえずAreaIdだけ書き換えます。割と早急に

**Comment by ponkotuy** [comment]
んーデプロイ無しで追記したいと思ったけど、1週間前に仕込むことも不可能ではないし、そこまでやんなくてもいいや。DBには入れる

**Comment by ponkotuy** [comment]
オラッ https://github.com/ponkotuy/MyFleetGirls/commit/36d46958cd6f6e452e789af1313f562e2e6dfb32

**Comment by ponkotuy** [comment]
修正漏れ https://github.com/ponkotuy/MyFleetGirls/commit/df1292894a172ff28c6c8d39352839050d577629
