### ISSUE TITLE
クライアントからサーバーへのデータ送信リトライ機能追加

### ISSUE THREAD

**Issue by b-wind** [ponkotuy/MyFleetGirls#115]
タイトルそのままだがデータ送信に失敗した際にリトライする機能を付けた方が良い。
主な目的はデプロイなどで一時停止した際のデータロストを防ぐ為。

検討・考慮すべき事項

* リトライ回数はどうするか
* リトライ間隔はどうするか
* データ送信の順序が重要な場合、リトライが発生した以降のデータ送信は待たせる必要がある（単純に送信待ちキューがあれば良さそう）

**Comment by ponkotuy** [comment]
順序考えてなかった。イベントドリブンに作ってあるから送信待ちキューではむりぽ。Lockか、Actorか（まぁ後者の方が事故は少なそう

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/tree/refactor-client とりあえずリファクタして整理しようとしたらこんなことになった

**Comment by ponkotuy** [comment]
とまあActorでシングルスレッドでPOSTされることが保証されるようになったので、MFGHttpにリトライ入れれば良いのではって感じだ

**Comment by ponkotuy** [comment]
Retry入れた。大規模にリファクタしてるし、大規模にテストした方が良さそうなのでみんなの力を借りる

**Comment by b-wind** [comment]
せやなぁ。ざっと見る限り大丈夫だとは思うけど流石に怖いという感覚がある。
最近再現性の低い不具合も出ているようだし。
