### ISSUE TITLE
練習巡洋艦の扱い

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#121]
どうすっべこれ。どこに入れよう http://myfleet.moe/user/355732/statistics

**Comment by b-wind** [comment]
今の情報では細かい差異は有る物の、軽巡洋艦に準じる部分は多そう。
ただし、ルート固定要因としては別物。構成に必須な遠征もある。
あと、演習の旗艦にすると取得経験値が上がるとか。

**Comment by ponkotuy** [comment]
んーまぁ放置でいいか
