### ISSUE TITLE
大鯨が出ない

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#126]
大鯨が！出ないんです！

**Comment by ttdoda** [comment]
朝霜と山雲も出ません!!

**Comment by ponkotuy** [comment]
出現率も分かる そうMyFleetGirlsならね！

大鯨 http://myfleet.moe/entire/sta/from_ship#query=%E5%A4%A7%E9%AF%A8&ship=184
朝潮 http://myfleet.moe/entire/sta/from_ship#query=%E6%9C%9D%E9%9C%9C&ship=425
山雲 http://myfleet.moe/entire/sta/from_ship#query=%E5%B1%B1%E9%9B%B2&ship=414

でも出ないものは出ないんじゃ。

**Comment by ponkotuy** [comment]
しかしこの画面凄い重いな。issue立てよう

**Comment by b-wind** [comment]
イベント海域だと出現率は難易度別だし、通常海域だと提督レベル別

**Comment by ponkotuy** [comment]
やっぱ難易度で出現率変わるのか。一応E-1を甲でクリアしておいて良かった

**Comment by ponkotuy** [comment]
立てた https://github.com/ponkotuy/MyFleetGirls/issues/127

**Comment by b-wind** [comment]
朝潮じゃなくて朝霜な……
そして E-4-H とかで総数が取れてないのなんなん。

**Comment by ponkotuy** [comment]
朝潮と朝霧良く間違えるよね←
あーE-4とE-5なんかバグってるのは認識している。issue立てるの忘れてたけど、イベント特別仕様かな。それっぽい話あります？

**Comment by b-wind** [comment]
うーん、E-4 連合艦隊でも無いし特別思い当たる事は今のところ無し。

**Comment by ponkotuy** [comment]
立てた https://github.com/ponkotuy/MyFleetGirls/issues/128

**Comment by ponkotuy** [comment]
こういう雑談スレみたいな奴面白いし、簡単になるissueとか出てくるので定期的に立てよう（ぉ

**Comment by ponkotuy** [comment]
https://twitter.com/ttdoda/status/567301999620673538 抜け駆けされた。つらい

**Comment by b-wind** [comment]
掘る暇なんて（）

**Comment by fetus-hina** [comment]
:+1:

**Comment by ponkotuy** [comment]
結局E-1面倒になって10回ぐらいしか回さなかったし出なかったよ…

**Comment by b-wind** [comment]
5-2 より 2-5 の方が下手したら出る感じになってるし、うちの艦隊には4人目来たしどうなってるんだ。

**Comment by ponkotuy** [comment]
1隻寄越せ〜w

**Comment by Butter-Knife** [comment]
うちは菱餅集めてるときに2人ぐらい来ました(・ω・)
既に龍鳳さん含め二人所属してたのでお帰り頂きましたが（・ω・ゞ

**Comment by ponkotuy** [comment]
くそっ、単なる廃人による大鯨自慢スレになっとるw

**Comment by ponkotuy** [comment]
いいもん！開発者特権で大鯨がいない人限定称号作っちゃうもんね！（おとなげない

**Comment by ponkotuy** [comment]
#215

**Comment by ponkotuy** [comment]
https://myfleet.moe/user/10007732/honor 大鯨でない

**Comment by Butter-Knife** [comment]
さっきマンスリー任務でで2-5行ったらポロッとでました…

**Comment by ponkotuy** [comment]
そゆのいいから！

**Comment by Butter-Knife** [comment]
出たらここで自慢しろって、頭の中で何かが…(・ω・)

**Comment by ponkotuy** [comment]
嫌がらせだ!w

**Comment by b-wind** [comment]
磯風かわいいなぁ。

**Comment by ponkotuy** [comment]
知らない子ですね

**Comment by Butter-Knife** [comment]
磯風なら1番ドックで寝てるぜ（・ω・）

**Comment by ttdoda** [comment]
磯風は'14夏イベントを全部クリアすれば手に入るんだから、ふつうみんな持っているんじゃないですか?
# Romaかわいい
# 高波もかわいい

**Comment by ponkotuy** [comment]
最後までクリアしたイベント今回が初だぜ！！！←

**Comment by ttdoda** [comment]
親潮が出ません!! (と、ここに書けば出ると聞いた)

**Comment by k-shin** [comment]
反対に大鯨のままケッコンしたへんｔじゃない紳士も有りかなと。

**Comment by ttdoda** [comment]
ちょうどLv99大鯨が居たので……
https://twitter.com/ttdoda/status/735431790412734465

**Comment by ttdoda** [comment]
https://twitter.com/ttdoda/status/735429088794398722

今度は春風が出ません!!

**Comment by ponkotuy** [comment]
大鯨かわいいからしょうがないね

**Comment by b-wind** [comment]
[![Gitter](https://badges.gitter.im/ponkotuy/MyFleetGirls.svg)](https://gitter.im/ponkotuy/MyFleetGirls?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by ponkotuy** [comment]
![cimg0386](https://cloud.githubusercontent.com/assets/4147492/15821144/f220aa92-2c28-11e6-9987-2fe934451a2b.JPG)
大鯨出た

**Comment by ponkotuy** [comment]
大鯨出たしcloseするね(ニコッ
