### ISSUE TITLE
一部の提督で個人の装備一覧が全く表示されない

### ISSUE THREAD

**Issue by mizunashi** [ponkotuy/MyFleetGirls#130]
![2015-02-17 21 50 48](https://cloud.githubusercontent.com/assets/1645189/6228423/192ce692-b6ef-11e4-9d0a-a78e6257b45b.png)
複数の個人において装備一覧が全く表示されなくなっています。
多くの提督は、通常通り表示されている。

確認されたのは2/17の夕刻以降であるため、ランカー報酬（100位以内）に配布された、新装備「熟練見張員　装備No.129」を受け取った提督に起こる現象である可能性がある。

**Comment by ponkotuy** [comment]
マスターに無いしマスター登録まわりのバグですかねー

**Comment by mizunashi** [comment]
本来は新装備が来た場合、マスターへは自動に登録される？ という事なんでしょうか。
別の視点から見て、マスターにデータが無い場合でも分かっている装備は正常に表示されるという仕様だったら、全く気づかなかったかもですｗ

**Comment by ponkotuy** [comment]
そう、その挙動が正しいのでその修正もしますが、そこそこ時間掛かるのでそれは別チケットで

**Comment by ponkotuy** [comment]
原因分かった。艦娘の更新と同時に処理してて、装備の更新だけ降ってくると変更されないらしい。面倒くさいので直接DBに突っ込む対応でお茶をにごす

**Comment by ponkotuy** [comment]
マスター入れてもなおらねーw なんじゃこりゃ

**Comment by ponkotuy** [comment]
複数あるのかも。正攻法で行こう…

**Comment by ponkotuy** [comment]
Hashチェック噛ました https://github.com/ponkotuy/MyFleetGirls/commit/21184893daa2448ea9620b73d199572b10ae9cab

**Comment by ponkotuy** [comment]
表示の修正issue https://github.com/ponkotuy/MyFleetGirls/issues/131
