### ISSUE TITLE
「ドック/Condition回復」に所属艦隊を示す表示が欲しい

### ISSUE THREAD

**Issue by fetus-hina** [ponkotuy/MyFleetGirls#132]
同名の艦を取っ替え引っ替えしているとどの艦の回復を待つ必要があるのかわからなくなるので、
艦隊を示す何らかの表示（数字/空白だけでもあれば充分かと）があるとうれしいです。

https://twitter.com/fetus_hina/status/567946330326179840

**Comment by ponkotuy** [comment]
すぐできそうだし僕もそれ欲しいと思ったのではやいうちにやります

**Comment by b-wind** [comment]
別 Issue 立てるべきかと思ったけど、遠征欄で遠征IDか対象海域が併記されてるとありがたい。

ああそうですよ、支援来ないと思ったら南方海域の前方支援任務に出してしまってただけですよ（）

**Comment by ponkotuy** [comment]
とりあえず所属艦隊の数字だけ。テストしてないから家でやる https://github.com/ponkotuy/MyFleetGirls/commit/4ebc56b083d336cb35206f35851b7a125d5a41ec

**Comment by ponkotuy** [comment]
Fix https://github.com/ponkotuy/MyFleetGirls/commit/4ecb9215a4ac4af6d541796fc9ac92d1f4e18942

**Comment by ponkotuy** [comment]
AreaID表示追加 https://github.com/ponkotuy/MyFleetGirls/commit/8458177470527b50fd0329ce8ab359107cff1f26
