### ISSUE TITLE
駆逐艦とかのドロップ表示を省略する

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#138]
特別多いところ覗いて「など」とか書けば良くね、っていう

**Comment by ponkotuy** [comment]
ついでにBattleResultのQuery削減しようと色々考えてみたけど無理っぽいのでやめた。とりあえずステージソートで50件にしてみた

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/tree/cut_drop

**Comment by b-wind** [comment]
どういうイメージだったの？

**Comment by ponkotuy** [comment]
あと必要な機能
* ドロップ率の高い順でソート
* 入手経路検索での対応

**Comment by ponkotuy** [comment]
BattleResultテーブルの集計テーブルを作る、集計早そうなDBを試してみる、キャッシュするetc

**Comment by b-wind** [comment]
海戦履歴 タブでの表示かな？

**Comment by ponkotuy** [comment]
回線履歴タブは全然重くなくて、ドロップ数総数の集計している箇所が問題

**Comment by b-wind** [comment]
把握。 集計テーブル作ってバッチ処理かなぁ。

**Comment by ponkotuy** [comment]
が王道ではあるがつまらないのでやらない（ぉ

**Comment by ponkotuy** [comment]
ドロップ率ではなくドロップ数でソートした。

**Comment by ponkotuy** [comment]
めでたくマージされました（セルフマージ
