### ISSUE TITLE
httpsへ完全移行

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#142]
http要らんくね、という話をした。確かにそうだ

**Comment by ponkotuy** [comment]
移行完了

**Comment by ponkotuy** [comment]
だめだ、updateツールとclientのpostがちゃんと動くことを確認しないといけなかった。

**Comment by ponkotuy** [comment]
変更多そうなのでbranch https://github.com/ponkotuy/MyFleetGirls/tree/https

**Comment by ponkotuy** [comment]
updateツールの変更。Redirect対応とhttps対応

**Comment by ponkotuy** [comment]
clientツールの変更。結果的には修正微量だったけどapacheのhttpclient分かりずれー

**Comment by ponkotuy** [comment]
updateツールのupdateはユーザにやってもらわないといけないので、できればこれ https://github.com/ponkotuy/MyFleetGirls/pull/148 と同時にやりたいんだけどはてさて

**Comment by ponkotuy** [comment]
移行の第一段階は完了して、client側は全部ssl対応済。次は3/19にSSLへの完全切り替え予定

**Comment by ponkotuy** [comment]
どうやらOracle JavaにはStartSSLのルート証明書が入ってないらしいので、標準でhttpsを使う設定とりやめたりした

**Comment by b-wind** [comment]
ざっと思いつく手段。試しては居ないけど方法論としては。

方法１ StartCom のルート証明書を クライアント環境にインストール
手順が面倒だし、ルート証明書弄るのはセキュリティ的にも好ましくない。

方法２ SSL のハンドシェイクを無効にする（証明書エラーを無視する）
なんの為に HTTPS にするのか分からなくなる。

方法３ 他の SSL サーバー証明書を導入
年額 2,000 程度の出費になりまーす。  

アプリケーション毎に証明書周り設定出来ればねー。（無さそう）

**Comment by b-wind** [comment]
ルート証明書の keystore を独自に作って同梱として配るのが一応手かな。
http://archive.guma.jp/2010/11/java-bitly-api-ssl.html
事実上 startcom ( startssl ) のサイトにしかアクセス出来なくて良いわけで。

**Comment by b-wind** [comment]
Rapid SSL なら 1300 円ほどだけどこれも JRE に同梱されているか若干怪しい。

**Comment by ponkotuy** [comment]
セキュリティ的にkeystore独自に配るのどうなんだと思ったけど、冷静に考えてプログラマ何でもできるしあんまり気にしなくていいか。とりあえずkeystore同梱を試す

**Comment by ponkotuy** [comment]
と思ったら既にできてるのか。後で見ます

**Comment by b-wind** [comment]
keystore 配布は確かにかなりの悩みどころ。
ただ、最初にアプリ全体をダウンロード（zip ファイルね）する場所が StartSSL で保証すると大抵のブラウザが判断したなら（まだ https のリンクになって無いけど）、ダウンロードしたアプリが同じ物を信用しても矛盾は無いかなーと。
ブラウザや各種ディストリの提供するキーストアを直接読めたりすればより良いんだけど、流石に面倒過ぎる。

**Comment by b-wind** [comment]
ぶっちゃけ HTTP のままだと DNS キャッシュポイズニング他、やり放題だしそれよりはマシって感じだ。

**Comment by b-wind** [comment]
myfleet_web#5 こちらもー

**Comment by ponkotuy** [comment]
ようやくおわったぜ！
