### ISSUE TITLE
Playframework の Gzip 転送設定

### ISSUE THREAD

**Issue by b-wind** [ponkotuy/MyFleetGirls#150]
https://www.playframework.com/documentation/ja/2.3.x/GzipEncoding

現状のコード見る限り、対応する設定では無い様に見える。
極端な性能改善とかは無いと思うけど、デメリットも少ないのでやってみてはどうか。
Filter 一つ追加する程度のようだし。

* 主に Web インターフェイス側での利用にメリットがある。
* MyFleetGirls サーバー・クライアント間の通信はこれとは別設定となる。

**Comment by ponkotuy** [comment]
:+1:

**Comment by ponkotuy** [comment]
MyFleetGirls.jarがでかくて不満だったし少しでも減るならありがたい

**Comment by b-wind** [comment]
どちらかと言うと、これの直接の影響は 各 API が返してる（はず？）Json とか HTML の方で。
MyFleetGirls.jar の圧縮対応は #148 のpsck200 対応が本命。

**Comment by ponkotuy** [comment]
PRに対応したissueかと思った。わかりづらい

**Comment by b-wind** [comment]
なるほど、タイミングは微妙だった。
静的コンテンツを圧縮転送するならこう言う Filter で動的にやるんじゃ無くて、
事前に圧縮済みのファイルを（非対応クライアント用にオリジナルも）配置するのがセオリーす。

**Comment by ponkotuy** [comment]
gzipはgzファイルを配置するだけで特に設定せずとも自動でgzを返す。で、事前に配置するのはsbt-gzip plugin突っ込むだけでいける

**Comment by ponkotuy** [comment]
そもそも静的なファイルだけgzip早くなんのかよ、と思って調べてみたら、JavaScript一式が静的ファイルだし、そこそこ効果ありそう

**Comment by b-wind** [comment]
@ponkotuy 公開アセットとかは controller.Assets が自前で対応してるね。
このフィルターは動的に吐き出したものを逐次圧縮してくれる物だと思うけど。

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/aec202b67dabe5aed50ca0d74959b33b5388c4ef やった
