### ISSUE TITLE
ユーザの艦娘一覧画面での艦隊構成表示の不具合

### ISSUE THREAD

**Issue by zaltoprofen** [ponkotuy/MyFleetGirls#153]
艦隊構成の表示が編成順でなくShipのId順に並んでいるっぽい？

* 実際の編成
![2015-03-10 10 23 56](https://cloud.githubusercontent.com/assets/4676932/6567747/2cef96b2-c710-11e4-9878-a99245f5fe73.png)

* MyFleetGirlsでの表示
![2015-03-10 10 24 18](https://cloud.githubusercontent.com/assets/4676932/6567749/3600d64e-c710-11e4-85d9-030404e5af4d.png)

* HTML(Ship idの確認)
![2015-03-10 10 24 36](https://cloud.githubusercontent.com/assets/4676932/6567754/44f6fbec-c710-11e4-98e3-2b84a79e58a6.png)

**Comment by zaltoprofen** [comment]
9d8457423cee80dbb8ed31b14d1a020dbc4914d1 で対応済み？
サーバに反映されてないだけ？

**Comment by ponkotuy** [comment]
はい対応済です。デプロイ忘れてました、すいません。デプロイ確認のちcloseします

**Comment by ponkotuy** [comment]
OK
