### ISSUE TITLE
Pack200 対応コントローラーの作成？ （ refs #148 ）

### ISSUE THREAD

**Issue by b-wind** [ponkotuy/MyFleetGirls#155]
現状サーバー側でのコンテントネゴシエーション で、pack200 には対応していない。
対応したコントローラーを作成するのが有効と思われる。

実装案の検討：
要求仕様のうち殆どは公開アセット用の controller.Assets に揃っているので、これを流用するのが近道に思える。
（ Last-modifed の対応、コンテントネゴシエーション対応のベース、ついでに Etag の対応とか ）
https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/controllers/Assets.scala

```scala
object Jar Assets extend Assets {
  // いろいろ
}
```

```
GET  /assets/*file        controllers.JarAssets.at(path="/public", file)
```

みたいな？（ この辺りまだよく分かってない）

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/820e8380cec2aac950d149cd3401b07a0d871253 結局全体を上書きしたというアレ
