### ISSUE TITLE
Snapshotリンク付与・改行

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#156]
という提案が来たけど、やるならまず仕様を詰めないといけない。

* URLっぽいのを全部リンク張るのか、日本語URL対応できるのか、その場合リンク終端をどのように判定するのかetc
* リンク有効にするとスパムが跋扈する可能性、対策必要なのかetc
* そもそも現行で改行どういう挙動になってるのか、マーク付けるのか
* いっそMarkdownとか対応する？

とかとか。ぶっちゃけると本人にイマイチやる気がない

**Comment by b-wind** [comment]
リンクはスパムとかセキュリティとか考え出すと相当しんどいので、具体的なユースケース聞いてそれを直接実装する方がマシだと思う。


改行は編集モーダルを見る限りそのまま通る。表示時に 改行コード -> <br> の変換するだけ。
あと登録時のフォームは複数行の奴になってない（一行入力フォーム）のでそこだけ置き換えられればベスト。

**Comment by ponkotuy** [comment]
改行だけとりあえずやるかー

**Comment by b-wind** [comment]
あとはやるとすればスペースを &nbsp; に買えるぐらいかなぁ。それ以上の表現力はぶっちゃけ要らなさそうだし。

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/1f5353f70a95a1c921b3fa35ac48bc0176b71893 改行を表示するように修正

**Comment by ponkotuy** [comment]
まぁあとは要らないでしょ。閉じます
