### ISSUE TITLE
提督経験値の仕様変更

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#158]
提督経験値（を含むbasicデータ）をどの程度の頻度で取得するかの仕様は割と変遷が多くて、

* 比較的沢山取ってた初期設定
* どうせ使わないと急激に絞り込んだ時期
* そのままグラフ載せちゃって一杯問い合わせが来てる今

って感じ。問い合わせへの対応が面倒くさいので、そこらへんこなれたmaterialと似たような仕様にしたい。materialは現状資源が数百変動したら保存する代わりに、1ヶ月以上前のデータは削るみたいなことをやってる

**Comment by b-wind** [comment]
1. 全部取るようにして間引く ：無難な対応
2. POST されたデータとレコードの新しい方から2つめを比較対象にして、閾値以上の変動 => POSTされたデータを INSERT , 閾値未満の変動 => ポストされたデータで最新レコードを UPDATE：アルゴリズムが面倒になるけどコードの変更は局所化される
3. 最新ステータスと変更履歴を別テーブルに：最新ステータスを他から参照する機会が多いならコードがシンプルになるが、おそらく大幅な変更が必要

**Comment by ponkotuy** [comment]
3やるなら単にキャッシュで良くね、って思うた。どっちにせよ現状ネックになってるわけじゃないのでやらない

**Comment by ponkotuy** [comment]
2は名案だしやる

**Comment by b-wind** [comment]
3 はまぁ DB 屋としてはこう言うやり方もあるんすよ、と言うところかな。デメリットもあるし今採用する理由はあまりないと思う。
２ のコストは気になるところだけど、同じくそこまで心配するほどでも無いだろう的な。

**Comment by ponkotuy** [comment]
3をPartitioningで実装すればいいのでは

**Comment by ponkotuy** [comment]
よくみたらちょっと違うわ

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/9b867719d4deb69bbec93ae74576628c934f7468
