### ISSUE TITLE
二番艦によって消費・更新装備や改修後装備が異なる事案（現在94高射装置のみ）

### ISSUE THREAD

**Issue by mizunashi** [ponkotuy/MyFleetGirls#163]
摩耶改二実装に伴う、改修工廠の仕様変更があります。

Statistics統計＞装備改修＞装備改修できる装備リスト＞94式高射装置

において、二番艦が（秋月 or 吹雪改二) と （摩耶改二）で、消費装備・更新装備そして改修後装備（新しく出来る装備）が異なる仕様になりました。
6→7, 7→8, 8→9, 9→10において、秋月（改）又は吹雪改二を使用する場合は10cm高角砲1つが消費装備として要求されますが、摩耶改二を使用する場合は12.7cm連装高角砲１つが要求されます。

10→新装備においては、秋月又は吹雪改二を使用する場合は10cm高角砲2つ、摩耶改二を使用する場合は12.7cm連装高角砲2つと、更新装備が倍になる訳ですが改修後装備（新しく出来る装備）が下記の様に異なります。

秋月（改）又は吹雪改二：10cm高角砲＋高射装置
摩耶改二：12.7cm高角砲＋高射装置

ちょっと表記方法から考えないといけない事案になるかと思われます。

**Comment by ponkotuy** [comment]
DBレベルでの変更になりそうですな…（uniqueの単位が変わる

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/7e9f30b892ac5df219c0be28860878c9e1a1c11f
