### ISSUE TITLE
SnapShot 検索に全文検索を

### ISSUE THREAD

**Issue by b-wind** [ponkotuy/MyFleetGirls#164]
１．艦名での検索は用途がいまいち分からない＆タイトルやコメントに艦名が含まれている場合に検索出来ない -> 必要なの？
（ 明石固定ルート とか あきつ丸堀り とか検索出来ないのはちとつらい
２．LIKE 検索でもダメじゃ無いけど複数ワードでの絞り込み検索とか出来ないし

検索対象の文字列全部に対して全文検索すればいんじゃね？
Mroonga と言うのが MySQL / MariaDB 向けに良いらしい （ MariaDB にはサブセットが同梱されてる ）
メインの使い方は Mroonga ストレージエンジンとしての利用。（既存の ストレージエンジンに日本語対応全文検索を追加する事も出来る）
http://mroonga.org/ja/
http://gihyo.jp/dev/clip/01/groonga/0003

**Comment by ponkotuy** [comment]
サーバに新しいソフトウェア追加するのいやだ…（メモリの問題もある

**Comment by b-wind** [comment]
MariaDB なら mroonga はすでにストレージエンジンとして組み込まれている。（まぁ 別に MySQL 由来の全文検索 INDEX でもいいんだけど
https://mariadb.com/kb/en/mariadb/mroonga/

全文検索付けるのスナップショットだけで十分だし、メモリへの影響は気になるほどでは無いと思うのだけど。
何もしないのに比べれば更新はインデックス更新分コストが上がるけど頻繁では無いだろうし、
参照に関してはフルテーブルスキャンかけるよりは遙かにマシという印象しか無いのだよね……
すでに数十万件のレコードが存在したりするの？

**Comment by ponkotuy** [comment]
なるほど知らんかった。snapshotにそこまでやるかっていう話はあるけど、面白そうだしやろう

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/ccfe3f7b2b5a22924fc2c9e718692e754f328277 index追加

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/d71f977ada52275ba445956dddcaef0e378c86b0 batch追加

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/a90b7ff91bcb3be013874188315640fd7cc72160 サーチエンジン切り替え

**Comment by ponkotuy** [comment]
サーバのplugin追加したので、本番環境でもMroongaエンジン動く筈
