### ISSUE TITLE
同一種類の艦とケッコンしているときの称号

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#172]
同じ嫁を多数揃えている人向け称号か。機能は簡単だが名前が思い付かない

**Comment by Butter-Knife** [comment]
（艦名）ハーレム
（艦名）天国
（艦名）の園
（艦名）ばかりの爛れた鎮守府
（艦名）だらけ

…カッコイイのは思いつきませんでした（´・ω・｀）

**Comment by ponkotuy** [comment]
（艦名）の園採用します！

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/1afa13d3fed52917871fd2dfbb72b9ba6e012d42
