### ISSUE TITLE
初心者でも設定できる簡単or無条件な称号追加

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#173]
初心者・中級者でも付けられるような称号が少ないという問題があり、拡充したいです。というので案募集

- [x] 未婚提督、独身カッコカリ（ケッコン0）
- [x] 駆け出し提督（Lv50以下？）
- [x] 第六駆逐隊を揃える（所有。図鑑ではない）
- [x] クソ提督
- [x] 第30、7、16、17駆逐隊

**Comment by donaco** [comment]
暁電雷響を持ってると第六駆逐提督とか、轟沈させたらブラック提督とか割りと付けやすそう？

**Comment by b-wind** [comment]
同類として任務に出てくる組みあわせ「第五船隊」とかｘｘ駆逐隊関連は作りやすそう。

**Comment by ponkotuy** [comment]
轟沈フラグを取るという悪魔の所業をついに実行するときがきたんですね！

**Comment by ponkotuy** [comment]
第六駆逐隊とかで称号作る案自体は良いのですが、もうちょっと煮詰めた方が良さそう。全取得で結成、改への改造で出撃、全ケッコンで何か（厨二力が足りなかった。誰か名案頼む）みたいにすると良いかな（結局難しい称号追加してるアレ

**Comment by ponkotuy** [comment]
全ケッコンで何かみたいなのはちょっとコレと被る https://github.com/ponkotuy/MyFleetGirls/issues/183 がケッコンは重いね

**Comment by Butter-Knife** [comment]
第6駆逐隊が歌ってるキャラソンにちなんで「鎮守府の朝チュン」とか…（・ω・）

**Comment by ponkotuy** [comment]
あーそれいいですねー。それは特殊称号として追加しましょう

**Comment by b-wind** [comment]
ドッグの解放や、母港の拡張に応じた称号は可能なのかな？

**Comment by ponkotuy** [comment]
どちらかというと不可能じゃないかな。3or4番目のドック使ってれば解放していると分かるけど

**Comment by ponkotuy** [comment]
独身カッコカリ https://github.com/ponkotuy/MyFleetGirls/commit/2d9d1e208312fc02ce9ac57cf2a372c20dc129cc

**Comment by ponkotuy** [comment]
駆け出し提督 https://github.com/ponkotuy/MyFleetGirls/commit/2d324af88d3a085c9ccd085cc912e3db85d7e368

**Comment by ponkotuy** [comment]
正直最近の艦これの編成任務増え過ぎてて全部実装するのかったるいので、欲しいのだけここに挙げてください。それだけ実装します。第六駆逐隊はぼくも欲しいので実装します

**Comment by ponkotuy** [comment]
あと利根筑はそんなの関係なく実装されます←

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/3c825d3d78249c8ad238834dd003a6be346a8e25 第六駆逐隊と利根筑と鎮守府の朝チュン追加

**Comment by Butter-Knife** [comment]
さっき思いついた案：
条件：n日(ヶ月)以上非アクティブ
「膝に矢を受けた提督」
もしサーバー側で自動的に称号設定できるのであればMFGユーザーのアクティブ率とか分かるのかなーって

**Comment by ponkotuy** [comment]
自動称号はちょっと無いなー。非アクティブをウリにするのもないなー…（作者が一時期非アクティブだったのがバレてしまう

**Comment by ttdoda** [comment]
望月提督の自分としては、三十駆(睦月、如月、弥生、望月)が欲しいです。
あと、最近人気がある七駆(朧、曙、漣、潮)は有ると嬉しい人がいるんじゃないかな。
他には揃えるのが比較的難しい十六駆(雪風、初風、天津風、時津風)、十七駆(浜風、浦風、谷風、磯風)も有ると自慢に使えるかも。

**Comment by Butter-Knife** [comment]
確かにちょっとネガティブな案でした…
ID１番（初期艦）がいない→「（初期艦名）はもう…」みたいのもさっき思いつきましたがまぁｗ

あとは曙関連でクソ提督ネタとか。嫁艦設定で「クソ提督」、Lv150達成で「末永くクソ提督」みたいな。
もしすでに似たのがあったらゴメンナサイ。嫁艦設定してる提督とケッコンしてる提督が一人ずつしかいなくて確認できませんでしたので（´・ω・｀）

**Comment by ttdoda** [comment]
クソ提督 :+1:

「アイドル提督」とかにあわせてLv合計200以上かな。
現状あるのは[これ] (https://github.com/ponkotuy/MyFleetGirls/blob/master/server/app/honor/ShipMaster.scala)を参照。

**Comment by ttdoda** [comment]
漣を集めて「ご主人様」というのも欲しいですね。

**Comment by ttdoda** [comment]
あとは[これ](http://dic.nicovideo.jp/a/艦隊これくしょん%3A呼称表)を見ると
* 霞→「クズ」、「クズ司令官」
* 初風→「バカ提督」
* まるゆ→「隊長」

があるけれど、クソ提督と比べて元の艦娘が連想しにくいからつらいか。
ドイツ艦を全部集めてAdmiralとかはあり?

**Comment by Butter-Knife** [comment]
初風は「ツチノコ提督」もあり？ｗ
ドイツ艦の称号いいですね。

中二臭いけど、メタ発言する艦娘を集めて「世界の理を知る娘達」
那珂ちゃん(ゲームが嫌いになっても…)、初風(私は何人目かしら)、
武蔵(たまにはブラウザを閉じるのも…)、綾波（邪魔なら音量下げて下さいね）、
巻雲（画面の中から…） このくらいだったかな

**Comment by ponkotuy** [comment]
クソ提督面白いですね。多分1行追加するだけでいけるんで、PRまで出してくれると更にいいですね！
Admiralはドイツ艦が増えたときどーすんだという問題がありむずかしい。
メタ発言分かり辛過ぎでしょうw
漣はまぁどっちでも…

**Comment by ponkotuy** [comment]
三十駆逐隊とかもいいと思います。こちらはMigration設定するだけですね

**Comment by QURAIN** [comment]
最上、電、五月雨、阿武隈などの衝突歴がある艦から「突撃艦」とか
同型艦すべてをかなり高レベルにまとめて、「○○型マイスター」みたいなのとかそういう感じですかね？

**Comment by ponkotuy** [comment]
良いけど初心者向けではない感じだ

**Comment by ponkotuy** [comment]
大分そろってきたし一旦closeします。欲しい人は別途issue立ててね！
