### ISSUE TITLE
更新してないのに更新しますと言われる

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#174]
MyFleetGirlsをデプロイするたびにdownloaderでダウンロード走るけど実際は1bitも変わってない。
問題は2点あって、

* デプロイスクリプトが更新無しでもファイル削除して生成しなおす挙動になってる
* これを解決したとしてもMyFleetGirlsのデプロイ先は2つあってデプロイ毎にスイッチしているので、更新日時がデプロイする度に変わる

という2つ問題がある

ぶっちゃけ解決めんどいしサイズ減らす方向で根本解決したい気もする

**Comment by b-wind** [comment]
正確に分かってるか自信ないのだけど、sbt が client サブプロジェクトで
/client/target/scala-{version}/MyFleetGirls.jar
を作るのだよね？
で、このファイルは client のコードを触ってない場合は変更が無い？

この前提が正しければ、都度の削除は無くした上で
``sh
cp /client/target/scala-2.11/MyFleetGirls.jar 長いので省略
``
部分を
``
cp -a /client/target/scala-2.11/MyFleetGirls.jar 長いので省略
``
としてタイムスタンプを維持すれば １つめの問題は解決するのでは。

２つめのはスイッチするスクリプトが分からないので何とも言い難いが、cmp コマンドで比較して差が無ければ古い方のタイムスタンプに修正するとか。

**Comment by b-wind** [comment]
タイムスタンプが古くてもロールバックするしようじゃ無いからどっちでもいい気はした。
重複したダウンロードが０にはならないけど、８割方無くせると。

**Comment by ponkotuy** [comment]
なるほど、更新日時を変えちゃう手があったか。それで良いと思います

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/b76a3e6fed8a86886452d539b48f90a190f67504 たったこれだけに6時間かかったんですよ…
