### ISSUE TITLE
jar file corrupt？

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#175]
http://gyazo.com/e9270bf2bf2f6b8ac4cb0bf6184e0597 みたいなjar fileがcorruptしてるというエラーが出る、らしい。2人ほどそういう報告来て、一人は解決したっぽいんだけど、もう一人はまだ出る、らしい。

JavaはOracle Java SE 1.8.0.31、らしい。

手元環境で、Oracle JDK 1.8.0.40で試してみたが再現しない。なんじゃろ？

**Comment by ponkotuy** [comment]
pack200まわりの不都合であるならば、pack200ダウンロード機能を切るオプション追加して解決する方法もあるが、なんにせよ再現しないので分からん

**Comment by ponkotuy** [comment]
何度やってもエラーっぽいから多分MD5がどうの、ではない

**Comment by ponkotuy** [comment]
とりあえずMyFleetGirls.jar直接落として試してよ、とアナウンス

**Comment by b-wind** [comment]
現状ダウンローダーの更新チェックが更新時間のみになってるから、ダウンロードに失敗してファイルが壊れてしまうとバージョンアップが無い限りそのままになってしまうと言うのはある。
そもそもなぜ壊れるかは不明ではあるけど。

暫定策としては ETag での比較にすれば、ダウンロードし直すことは出来る。
一応 Play の Assets コントローラーの実装的に Etag は ファイルの sha1 と更新時刻から生成されている（のだと思う）
https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/controllers/Assets.scala#L187

**Comment by b-wind** [comment]
とりあえず、直接ファイル上書きはやめて一時ファイルに書き出し -> ダウンロード後入れ替えのやり方にすれば多少は改善しそうな。
Exception も出てないけどファイルは壊れてるとかにはこれでは対応出来ないが。

**Comment by b-wind** [comment]
念のために記述しておくと、自分はこのエラーはダウンロード時の何らかのエラーによるファイル破損では無いかと考えている。
その為、エラーが発生したタイミングでは Exception は出ていると思うが見逃した、もしくはそもそも update.jar をダブルクリックしているなどの為に気がつかなかったのではと推測。

２度目以降はエラーになら無いのは前述の通り。

**Comment by ponkotuy** [comment]
ありがとうございますー家で動作確認してみます

**Comment by ponkotuy** [comment]
当人からの返事は駄目、らしい。なんか正直とても属人的なエラーな気がしてきたぞ

**Comment by Butter-Knife** [comment]
さっき1.3.7への更新時に同じようなエラーが出ました。やってみた解決策としては
JavaのUpdate(1.8.31 → 1.8.40) ×
downloaderをMFGサイトからDLして中身を上書き ×
↑の状態でMyfleetgirls.jarのみ削除してdownloaderでDLしなおす ○
こんな感じでした。PCはSurface Pro 2、Win8.1 Pro 64bit、Javaは32bit という環境です。

**Comment by ponkotuy** [comment]
時間何時頃ですか（実は何度かデプロイし直してたのでそれが原因かも

**Comment by b-wind** [comment]
#181 適用前のダウンローダー使ってると二重起動であっさりファイルが壊れる気はする。
壊れた後は次のアップデートがあるまで自動では更新されないのは今のところ仕様どおり。

1. ダウンローダーを更新
2. MyFleetGirls.jar を削除
3. 再度起動

を FAQ として載せるべき事案と言う気がする。

色々思い当たるパターンとかはあるけれど、結局それぞれの対策を入れる前のダウンローダー使ってるとアウトなので…… ダウンローダー自体の更新も欲しいかなぁ？

**Comment by ttdoda** [comment]
自分が遭遇したケースだと、MyFleetGirls.jarの中身がHTTPのリダイレクト応答になっていました。

**Comment by ponkotuy** [comment]
なるほど。折角FAQあるし纏めようか https://github.com/ponkotuy/myfleet_web/issues/8
我こそはという人はぜひ立候補していただき（ry

**Comment by b-wind** [comment]
まず FAQ に載せて対処して貰う。
大半の問題は一時的だったりするし、ユーザーとしてはすぐに動くのが第一だし。

その上で原因なり症状が分かる物に対しては報告して貰って個別に検討する。
今のところ「jar ファイルが壊れてて動かない」という大きなくくりに対してはそう言う結論で良いのでは。
jar ファイル壊れてないけどなぜか該当のエラーでて動かないケースは…… 見つかったら考えよう？

**Comment by ponkotuy** [comment]
でいいと思うよ

**Comment by Butter-Knife** [comment]
すみません返信見逃してました。
先に書いた現象が起こったのは今日(2015/04/03）のAM9時～9時半ぐらいだったと思います。

**Comment by ponkotuy** [comment]
AM9時はサーバ側の問題じゃないですねぇ。通信経路とかの問題だし、さっきdeployした https://myfleetweb.herokuapp.com/entire/about/faq#jar_error を参照しましょう
