### ISSUE TITLE
均等に育ててる提督サンが得やすい称号

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#183]
艦娘を比較的均等に育ててる提督向けの称号が圧倒的に足りないので追加したい。

提督Lv80〜提督Lv100ぐらいの人で均等に育ててる人なら獲得できそうな難易度ぐらいで設定したいですね。

具体的にはLv○以上の艦が○隻以上とかですかねー

**Comment by donaco** [comment]
lv５０以上の艦娘が五十隻で ハーフ＆ハーフ とか。ピザコラボしてたし。

**Comment by ponkotuy** [comment]
本当にそっちかな 五十鈴提督さん？

**Comment by ponkotuy** [comment]
まぁでも妥当なラインっぽいなー。それにする

**Comment by ponkotuy** [comment]
しかし名前はもっとなんとかならんのか

**Comment by ponkotuy** [comment]
精鋭の大艦隊でいいや（ベタ

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/d312f6e78883cd31c1fce0c2d15b9fe289f3b814
