### ISSUE TITLE
真Clientのhttps POST対応

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#184]
現行のClientはhttps POSTに対応するため、URLを強制的にhttpsに切り替える仕様になっている。
だがこの仕様はテスト環境的に好ましくないのと、Redirect時に307を返せばちゃんとRedirectできるという情報もあるので、

* nginxに307を返させるようにする
* httpsへの強制切り替え実装を削除する

をやる

**Comment by b-wind** [comment]
#180 これで行けると思うよ。

**Comment by ponkotuy** [comment]
まじか。ちゃんと見てなかった。確認します

**Comment by b-wind** [comment]
コメントあっさりしすぎてたかも知れない。直します。

**Comment by ponkotuy** [comment]
いける！と思ってマージしたもののできなかったのでrevertした

**Comment by ponkotuy** [comment]
エラーの内容がGET /hoge にアクセスできなかったとか言っていて、お前は何を言っているんだ状態

**Comment by ponkotuy** [comment]
あと307を返すようにしてもだめだった

**Comment by ponkotuy** [comment]
多分LaxRedirectStrategyはPOST, PUTもREDIRECTする（GETで）だと思う

**Comment by b-wind** [comment]
改めて見直したけど、301, 302 はともかく 307 は行けそうなんだけどなー

**Comment by ponkotuy** [comment]
結局手でRedirect書いた https://github.com/ponkotuy/MyFleetGirls/commit/774ce5ece7341fd9ebca0632f261c1bb7fc4b982
