### ISSUE TITLE
阿賀野型が出ない。

### ISSUE THREAD

**Issue by ryokucha175** [ponkotuy/MyFleetGirls#217]
能代とぴゃあっ！が出ない！

**Comment by ponkotuy** [comment]
（ぴゃあっが分からないとは言えない空気

**Comment by ponkotuy** [comment]
酒匂かー。6-2のみドロップとかつらぽよですね

**Comment by ponkotuy** [comment]
能代は大型の最低で2%。んー言うほどレアでもない気がするが…まぁいいか

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/dd7dcfbb8b9024dca7d3c5c08bcaa5421bcd158a サクサクっと

**Comment by ponkotuy** [comment]
なお、「○○が出ない」の条件はこちら https://twitter.com/MyFleetGirls/status/589776407858843648
