### ISSUE TITLE
MyFleetGirlsへポストするClientの制限

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#226]
MyFleetGirls自体はオープンソースだし好きにすればいいんだけど、公式で配布しているMyFleetGirlsClient以外でMyFleetGirlsサーバへ艦これデータをPOSTするのを原則禁止にしたい。

最大の理由は幾らかのAPIが悪意・バグで操作されるとMyFleetGirlsを壊すに足るだけの脆弱性を抱えているため。あとはデータを操作されることで統計データへの信用性が揺らぐ点、下手に弄られて負荷が高まる点を危惧している。

ただユーザ的にも色々言いたいことがあるかもしれないので、何か意見がある人はここへどうぞ

**Comment by nekopanda** [comment]
それはつまり、クライアントのバグ修正などをこちらでしたい場合でも、テストは自分でサーバを立てて行えということですか？

**Comment by ponkotuy** [comment]
んんー、開発時のことは考えてなかった。そこは例外にしてもいいかも

**Comment by ponkotuy** [comment]
とはいえその抜け穴えらい広いからどうしたもんか、という所ではある

**Comment by nekopanda** [comment]
あと、技術的にはどうやるの？jarを逆コンパイルしたら鍵が分かっちゃうとかじゃない？

**Comment by ponkotuy** [comment]
無理なのでルールでやるしかない。逆コンパイルしなくてもソースコード公開している以上、かなり難しいのは確か

**Comment by nekopanda** [comment]
ちょっとツイッター見てきましたけど、この件は #225 の修正版を私がしたらばで公開したらからそういうのを阻止したいということですよね。

私としては、航海日誌拡張版や七四式とMyFleetGirlsが併用できないという苦情が来たので、仕方なく動いたのです。そちらがこの問題に対する調査と修正を行っていれば私が動く必要もなかった。MyFleetGirlsと併用で問題が出たのこれが初めてではありません。MyFleetGirlsのプロキシがzipで圧縮して返すせいて、こちらはMyFleetGirlsと併用するためだけに解凍するコードを追加したこともありました。

こちらが善意でMyFleetGirlsの利用者さんのためにやったことが迷惑がられてしまうとは、とても残念です。

**Comment by ponkotuy** [comment]
善意が常に全員にとって幸福になるとは限らないのが悲しい世界ですね。クライアントに配るだけのツールなら好き勝手にどうぞしても良いのですが、サーバを用意する必要があるツールである以上、サーバ側で問題が発生すると利用者全員とぽんこつさんが困るのです。

手続きとしては問題が発生して修正方法も分かってるならPullRequestを出すのが一番ですよ。原因不明だけど問題があるならissueを立てるとか。

**Comment by Butter-Knife** [comment]
んんー、開発とかについては門外漢なのですが、作者さんの与り知らないバージョンが配布されていて、潜在的にＭＦＧのサービス自体に悪影響を与える可能性があるってことですよね？
配布前にここで報告するなりＰＲ出すなりしておけばよかっただけなんじゃないかと。
善意のつもりでもそれなりの手続きを通さず、結果的に迷惑かけちゃったら悪意と変わらないと思います（・ω・）。

「お前の車、タイヤが減ってたから俺が自腹で交換しといてやったぜ！一本だけな！」
みたいな印象を受けましたｗ

**Comment by Butter-Knife** [comment]
てなこと書いてたらぽんこつさんも同じこと書かれてましたｗ

**Comment by nekopanda** [comment]
なるほど、それは申し訳ありませんでした。
それなら、ソースをforkしてビルドするとそのままの状態でMyFleetGirlsのサーバと通信してしまうことが問題ではないでしょうか？てっきりそういうのに対して寛容なのかと思ってしまいます。明示的にソースを修正しないとMyFleetGirlsのサーバと通信するようにならないのなら、それは勝手にMyFleetGirlsのサーバと通信してはいけないと分かると思います。

**Comment by kxbmap** [comment]
制限かけるのは問題無いだろうけど、言われてる通り技術的には無理な話なので根本的には脆弱性の方を何とかする必要がある。
データ操作に関しては分かりやすい奴ならユーザーのBANとそのユーザーからのデータを削除できる機能があればいいけど。

開発時に関して自分は本番に繋げる必要は感じてないのでどちらでも。
接続先はconfで明示的に指定しなければいけないはず。

**Comment by nekopanda** [comment]
接続先はconfで指定しますが、ちょっと自分でビルドしてテストしたいとかだとconfをそのまま持ってきて動かしてしまうので。接続先はソースコードに埋め込んで、公開ソースは接続先を消しておいて、そこにコメントで独自ビルドしたものはMFGのサーバと通信しないようにって書けばいいのではないかと思います。

**Comment by nekopanda** [comment]
あと、一応配布前にPullRequestは出しておきましたよ

**Comment by ponkotuy** [comment]
脆弱性に関しては仕様の問題なのが厄介。現状の規模だと悪意あるユーザはいないという前提に立って、躍起になって脆弱性を埋めるより、利便性を重視したいところ。ユーザがもっと増えてきたら緊急度が変わってくるかもしれない。

制限かけるのが技術的に無理なら、やはり無闇やたらに繋ぐな、ってQ&Aで書くぐらいしかない気がしてきたのでそうします。艦これツールに対する艦これ公式の見解みたいな感じだ。

**Comment by ponkotuy** [comment]
confに関しては特に変更する必要性を感じないです。気をつけるなりconfに工夫するなりしてください

**Comment by ponkotuy** [comment]
既存ユーザに影響を及ぼさない範囲でのconfまわりを修正するPRは勿論受け付けますが

**Comment by slime7** [comment]
Because of unstable mfg client proxy, I need a way to post data to mfg server without mfg client.

Perhaps you can make mfg client receive game response data from other tools then format and post them to mfg server.

![2](https://cloud.githubusercontent.com/assets/8674371/21585060/c9de03d4-d0f3-11e6-9a08-b08a2263f9db.png)

**Comment by b-wind** [comment]
@slime7 Please use mfg ver 1.5.14 or later. We updated network library, so stability has improved.

> Perhaps you can make mfg client receive game response data from other tools then format and post them to mfg server.

It is very difficult for technical reasons.

**Comment by b-wind** [comment]
だいぶ放置されてるけど、
「サーバー運用に責任持つのはぽんこつさんなので勝手クライアントは止めて欲しい」と言う主張で良いと思うし、どこかで明言しておけば良いのでは。
すでに改変版を作ろうとする人もほぼ居ないと思うので個別に何かする必要は無さそうと言う事で close ?

**Comment by ponkotuy** [comment]
https://myfleetweb.herokuapp.com/entire/about/faq#another_client
書いた
