### ISSUE TITLE
各種ツール群との連携強化

### ISSUE THREAD

**Issue by b-wind** [ponkotuy/MyFleetGirls#232]
とりあえず何が必要そうで、何はやらないか主な方針を。
色んなユーザーも増えたようだし、一度洗い直しを。

現状よく見かけるトラブル例
1. Client Proxy の SSL 非対応
2. 上位 Proxy の非対応
3. 多段 Proxy 時の設定の困難さ
4. トラブったときの情報源や問い合わせ

1 は現状 proxy.pac での対応になってるわけだけど、ユーザーからすれば一番分かりにくいところだろうとは推測される。特に多くの専ブラ・ツールで独自で ｒ 設定など出来る場合に混乱しやすい。
※ 専ブラの proxy 設定だとダメなケースが多い。
※ 下手をすると Firefox / Chrome に対応してないと勘違いされてるケースまである
重要が多そうな反面コーディングが面倒くさそうに見える（ 例とか殆ど無い ）

2 は逆に多くのツールが上位 Proxy を指定出来る事で早急の対処は必要なさげ。
とはいえ組みあわせ方の制限が多くなるし、対応した方が嬉しい人は多そう。
っていうかデバッグ用に自分が使うし（）

3 はまぁ苦労したい奴が苦労すれば良いんじゃ無いかな。こちらで援助してあげられることは殆ど無さそう。
まとめ Wiki 的なところにお任せで。

4 についてはどうするべきかは難しいところ。
ユーザーフォーラムなどで上手く回れば良いが、その為にいちいちサイト作ってアカウント作って貰って…… は正直大げさすぎる。
従来から有る FAQ を充実させると共に、公式 Twitter で定期 Tweet 等でアナウンスするのはやった方がよさげ。（ 割と導入時以外見てない・存在自体知らない事は多そう

ざっと思いつく限りでこんな所？

**Comment by ponkotuy** [comment]
12に関してはissueにしよう。やるかどうかは別にしても。2はそんな手間掛からんと思う
3はまぁ言うとおりです。
4に関しては艦これツール作者同士でなんかパイプ欲しいなーと思うことはある。が思うだけで具体的な案は無い。

**Comment by b-wind** [comment]
1. 2. は対応済みだし、3 はやること無い。 4 は色々状況変わってこの流れで話すことでも無くなった。
