### ISSUE TITLE
称号追加

### ISSUE THREAD

**Issue by ryokucha175** [ponkotuy/MyFleetGirls#233]
フェチ・性癖的な称号も欲しいなと思いまして、個人的に欲しいのが
黒タイツ・黒ストフェチ、メガネフェチです。

対象となる艦娘が(漏れがあるかもですが)
【黒タイツ・黒スト穿いてる艦娘】
比叡(無改造・改)、霧島(無改造・改)、大鯨、龍鳳、千歳
愛宕、夕張、睦月、叢雲、浜風、野分、香取
時津風

【メガネっ娘】
霧島、武蔵、Roma、鳥海、大淀、望月、香取
伊8、巻雲

でしょうか。
取得条件については、対象となる艦娘を一定以上所持していて
合計である程度の練度以上とか・・・？

**Comment by ttdoda** [comment]
メガネっ娘はあと、伊8、巻雲がいますね。

課題としては、今後対象艦が増えた時にどうするかですね。
メガネっ娘は自分が適宜Pull-Requestを出すようにしてもいいですが、
それ以外の属性は自分だと見逃す可能性が高いので他の人が行う必要があります。

**Comment by ponkotuy** [comment]
メガネっ娘はおれがやるぜ！という発想とても好きです

もし取得ONLYでよければ https://github.com/ponkotuy/MyFleetGirls/blob/master/server/app/honor/FleetGroup.scala で実装しますが、数が多いので対象艦の合計Lv、辺りが適切な気がします。

**Comment by ryokucha175** [comment]
おっと、、失礼しました。。

自分は開発は出来ないのでPull-Requestは出せませんが、
黒タイツ・黒ストの子が増えた時にissue立てる事なら出来ます・・！

**Comment by ponkotuy** [comment]
いやまぁ簡単だしPullRequest出せばいいと思います

**Comment by Butter-Knife** [comment]
黒スト、黒タイツは時津風、長月、若葉、暁もかな？
後ろ3隻は中破が控えめなのでニーソである可能性もありますが（・ω・ゞ

**Comment by ryokucha175** [comment]
プログラマさん怖い(；´Д｀)

あー、時津風はローライズが個人的にNGなので勝手に除外してました←
その3隻もですが、菊月もちょっとわかりづらくて除外したんですけど、
どうしましょうね。

**Comment by ponkotuy** [comment]
おれは 実装しか しない（丸投げスタイル

**Comment by ponkotuy** [comment]
あと称号名どうするかも悩ましいですね。「黒タイツ・黒スト」は長いからやりたくなくて、いっそどちらかのみにするという手を考えている

**Comment by Butter-Knife** [comment]
「黒脚大好き」とかどうでしょう？

**Comment by ryokucha175** [comment]
黒脚だとニーソとかも含まれちゃう感じがして、
黒タイツか黒スト、どちらかなら黒ストにまとめちゃいたい感じですね。

**Comment by ponkotuy** [comment]
黒ストに纏めるとしたらどの艦になります？

**Comment by ryokucha175** [comment]
あ、名称だけじゃなくて対象の艦娘も絞ります？
てっきり対象の艦娘は一緒で、名称が長いので名称だけどちらかに
って事だと思いました。

**Comment by ttdoda** [comment]
対象の艦娘が明確になっていないから、明確にしましょうという事ではないでしょうか?
こだわりが有るのならば絞ってもいいと思いますが。

後は条件ですね。「対象の艦娘を全部持っている」だと全艦娘を集めている人も対象になるので
あまりフェチっぽくないです。
やはり練度の合計でしょうか。その場合でも閾値をいくつにするかですね。
対象の人数が比較的多いので、それなりに高くした方がいい気がします。
仮に対象を14人として、各50とすると700、二人くらい99に行っているとして800とか。
いっその事1000くらいにしてもいいのかも。

ちなみに自分の所のメガネっ娘の練度合計を計算したら1897でした。

**Comment by ponkotuy** [comment]
> 対象の艦娘が明確になっていないから、明確にしましょう
いえす、その通りです。細かいところまで仕様が決まらないと実装できないっす。「黒スト」にしたら微妙に対象が変わるのでは、という危惧もあります。

Lv合計に関しては対象艦娘人数x50ぐらいが適切じゃないかと思います。あんま難しくしてもなー、というのが本音ですねw

ちなみに改二だけ対象から外すとかはしたくないです。改二にしちゃいけないのは直感に反するので

**Comment by ponkotuy** [comment]
とりあえずメガネフェチ入れたよ https://github.com/ponkotuy/MyFleetGirls/commit/9f31933c66a44af416ee8aa871494e78312344c0

**Comment by ttdoda** [comment]
:+1

**Comment by ponkotuy** [comment]
音沙汰がないのでcloseします
