### ISSUE TITLE
StartSSLの更新

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#237]
らしきメールが来てた

**Comment by ponkotuy** [comment]
8/23までっぽいしもうちょっと後でもいいや

**Comment by ponkotuy** [comment]
もうちょっと後でもいいんだけど、StartSSLから変更したい。要件は

* OracleJDKとOpenJDK両方に認証局の証明書が入っている奴
* 年間5000円以内
* 認証者証明とかワイルドカードとかは要らぬ

**Comment by ponkotuy** [comment]
このタイミングでmyfleet.ponkotuy.comを廃止してもいいかも

**Comment by ponkotuy** [comment]
使ってる人がちょいちょいいるのでリダイレクトがいいかな…

**Comment by b-wind** [comment]
本来 OpenJDK にはルート証明書は同梱されていないようなので、OS やディストリビューションの方で用意しているのでは無いだろうか。

**Comment by b-wind** [comment]
あと、あまり大きな違いでは無いけれど Firefox に同梱されるルート証明書と、
IE / Chrome は基本的に OS の用意している証明書ストアを使用するので最低限 Windows と OS X の証明書ストアにルート証明書が入っている事が要件になるかな。

**Comment by ponkotuy** [comment]
フムンなるほど。StartSSLですらOracleJDK以外入ってたから多分問題ないと思うけど、留意しておきます

OpenJDKはそうだったかー。多分OS or ディストリの対応と同じだろなー

**Comment by b-wind** [comment]
現実的には Win / Mac 位は対応してないと売り物にならないので国内で見かけるところは少なそう。
あと、対応状況自体は証明書ベンダー自身のページに大抵書いてあるので一応確認しておいた方が良い程度。

**Comment by ponkotuy** [comment]
myfleet.ponkotuy.comはどさくさに紛れて廃止したので関係ないっす

**Comment by ponkotuy** [comment]
ああそろそろやんないとやばい

**Comment by ponkotuy** [comment]
うわあああ

**Comment by kxbmap** [comment]
今年末だったらLet's Encryptが使えるようになってるはずなんだけどね

**Comment by ponkotuy** [comment]
おわった。思い付く限り最悪の結末だったが、まぁもっと早く準備しような
