### ISSUE TITLE
対空カットイン可・不可の表示

### ISSUE THREAD

**Issue by b-wind** [ponkotuy/MyFleetGirls#243]
主に個別艦毎の表示になるけど、その時点の装備で対空カットインが可能かどうか表示してあげると便利かも知れない。
ただしアルゴリズムがちと厄介。

**Comment by ponkotuy** [comment]
アルゴリズム次第な案件だ。変な定数が入ってたり、変数が多かったらキモッ、って言う準備はできている（実装しないとは言ってない）（実装するとも言ってない

**Comment by ponkotuy** [comment]
やるかー

**Comment by ponkotuy** [comment]
アルゴリズム結構しんどそう http://wikiwiki.jp/kancolle/?%B9%D2%B6%F5%C0%EF#antiairfire

**Comment by ponkotuy** [comment]
固定ボーナスの高い順に判定していけばいいんだろうか

**Comment by ponkotuy** [comment]
高射装置付き高角砲がEquipType上高角砲扱いなので特別扱いする必要がある。マジ艦これのプログラマクソだぜ

**Comment by ponkotuy** [comment]
できたけどどこに表示されると便利なんだろうコレ

**Comment by ponkotuy** [comment]
艦娘タブの艦隊表示でLabelで付くと良いかも

**Comment by ponkotuy** [comment]
できた。どうせバグってるだろうしバグ報告待ちと洒落込みますかね(ひどい

**Comment by k-shin** [comment]
対空型の艦が実装される度にsource修正するの？

**Comment by ponkotuy** [comment]
そうなるなー
