### ISSUE TITLE
任務の手動達成対応

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#245]
任務達成時に送信失敗すると永遠に達成できない問題があり、まぁ手動で達成にしときたいよね、っていう奴

**Comment by b-wind** [comment]
間違えて達成にしてしまった場合の対処方法も必要になりそう。

**Comment by ponkotuy** [comment]
間違えて達成にしてしまった状況が想像できない

**Comment by b-wind** [comment]
なるほど。じゃあ無くて良いのかも。

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/8580164b6c384170705f8873beeb4d6d9f5f7cbf
