### ISSUE TITLE
○○提督の称号が得られない

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#248]
かぼちゃ提督から、大井と金剛の該当称号が無いと言われた https://myfleet.moe/user/777804/top

**Comment by ponkotuy** [comment]
というか称号があからさまに少ないような気がする。ほかにも漏れてそう

**Comment by ponkotuy** [comment]
こんな廃人提督がこんな称号少ないわけがない

**Comment by ttdoda** [comment]
ShipMasterは上位5隻に制限していませんか?

https://github.com/ponkotuy/MyFleetGirls/blob/master/server/app/honor/ShipMaster.scala

**Comment by ponkotuy** [comment]
うわー！なんで制限したか覚えてねー！撤廃します…

**Comment by ponkotuy** [comment]
きっと当時のぽんこつさんには深淵な理由が…ぶつぶつ…

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/d4ce12437aaf510c2bb1b8112d16bc69d7ea1325
