### ISSUE TITLE
[Server]application.conf.sampleの廃止

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#251]
Playframeworkの設定ファイルapplication.confがサーバ設定ではなくアプリケーション設定を指向しているので、application.conf.sampleを廃止、application.confを常時置くようにして、サーバ設定(DB設定とか)は環境変数に逃がすとかする

**Comment by kxbmap** [comment]
一応
```hocon
foo.bar = "default value"
foo.bar = ${?FOO_BAR_ENV}
```
これで`foo.bar`は`FOO_BAR_ENV`が定義されてたらその値、なければデフォルト値になるよ

**Comment by ponkotuy** [comment]
それうまく動いた試しがないのよね…

**Comment by ponkotuy** [comment]
これでバグやらかしたので優先度上げて対応する

**Comment by ponkotuy** [comment]
local.confをincludeする仕様にした
