### ISSUE TITLE
Clientにライセンス情報付与

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#252]
Clientにライセンス情報ちゃんと付けないといけない

**Comment by b-wind** [comment]
https://github.com/sbt/sbt-license-report
これとか使うと楽になりそうだけど、どうじゃろ。

**Comment by ponkotuy** [comment]
おお、試してみるか

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/5db4f88e2fefabf9b693e4feb666c644b94dbfad
https://github.com/ponkotuy/MyFleetGirls/commit/041e0939df75125803f794aace7b46101d78739d

**Comment by ponkotuy** [comment]
手元でテストすればいいんじゃないかな（出先だった

**Comment by ponkotuy** [comment]
動作確認した。deployしよう
