### ISSUE TITLE
[Client]デフォルトのconfを用意する

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#253]
application.confが無かったら自動生成すればいいんじゃね、っていう話。ただし挙動が若干変わる。

application.confを作らない人は

今まで→デフォルト設定が変わると勝手に追従
これから→デフォルト設定が変わっても変化しない

**Comment by kxbmap** [comment]
デフォルト設定が欲しいならデフォルトのconfファイルをjarに含めて、`Config.withFallback`使うのがいいと思う。
同じことは`reference.conf`を置いて`ConfigFactory.load()`使えば自動でやってくれる。

**Comment by ponkotuy** [comment]
新しい項目が追加されたときのことを考えるとそっちの方がいいかも

**Comment by b-wind** [comment]
application.conf.sample はデフォルト設定と言うよりは「こう言う設定項目がありますよ」という例示なのでして。
ぶっちゃけ application.conf が無いときのフォールバックとして使っている現状が変。

**Comment by ponkotuy** [comment]
ぐぬぬ、実装した当時は名案だと思ったんだがなー
