### ISSUE TITLE
○○出ない称号拡充計画

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#255]
○○出ない称号は「イベント以外で入手可能だけど入手困難な艦」、という条件です。最近通常海域でドロップするようになった艦がちょいちょい出たと聞いたので艦を増やそうかと思ってます。

現状ぼくが把握してるのは、

- [x] 春雨
- [x] 香取
- [x] 雲龍
- [x] 伊401
- [x] 三隈
- [x] 初風
- [x] 矢矧
- [x] 早霜
- [x] 清霜
- [x] 朝霜
- [x] 野分
- [x] 朝雲
- [x] 大淀
- [x] 谷風

ですかね。他にあれば下にどうぞ

**Comment by Butter-Knife** [comment]
そういえば 伊401出ない はありましたっけ？
大型建造か6-1のハズレマス(H)でドロップするみたいですが（・ω・ゞ

**Comment by ponkotuy** [comment]
無いですね、追加しましょう

**Comment by ponkotuy** [comment]
三隈もかなりレアだし入れて良い気がしてきた

**Comment by ttdoda** [comment]
通常海域での入手が大変だといったらやっぱり初風ですね。
大型建造+6-2の矢矧も能代と同程度に入手しづらいと思います。
阿賀野も入手手段が限られていますが、5-4は周回が楽だからいれるべきかどうか。

後は4-5組(早霜,清霜,朝霜,野分)ですかね。
4-5ではZ1もでますが、遠征で確実に手に入れられるので対象外かな。

**Comment by ttdoda** [comment]
他に、朝雲(1-6), 大淀(1-6), 谷風(3-5)辺りも入れていいかも。

**Comment by ponkotuy** [comment]
5-4で出るとレア感あんま無いですねぇ…

**Comment by ponkotuy** [comment]
んー結構多いな。まぁいいか
