### ISSUE TITLE
2015/07/17のメンテ後の不具合

### ISSUE THREAD

**Issue by Butter-Knife** [ponkotuy/MyFleetGirls#269]
・新規実装の 阿武隈改二 がMFGサイトで表示されない
・出撃の際、クライアントの EnemyIDが「会敵せず」になる
（戦闘終了後の敵艦隊名とドロップ艦は表示されてるっぽいです）

うちで気付いたのはとりあえずこれだけです。

**Comment by pinterior** [comment]
マスタデータが更新されないのは ApiStart2.scala に余計なスラッシュがあるからではないかと思うのですが、どうでしょう。
(壊されないためにわざと入れているのだったらすいません)

**Comment by ponkotuy** [comment]
おっしゃる通りでしたが、それだけではなかったので(どうも仕様変更が入ってるっぽ)、もうちょい頑張りまふ

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/a94a3d82e32d4c15fb33087b1acfb03f259cc570 とりま修正deploy

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/5b4d702e1dcfbd7b5ec88679549525347c1bfde4 敵ID表示を削除

**Comment by ponkotuy** [comment]
実害ないしdeploy急がなくてもええやろ…
