### ISSUE TITLE
イベント難易度別でのドロップ率集計

### ISSUE THREAD

**Issue by ttdoda** [ponkotuy/MyFleetGirls#272]
イベント海域でのドロップで丙では出ない場合があるようなので、難易度も取得しておいて
艦娘ドロップでのフィルタで難易度も指定できるようにしてほしいです。

**Comment by ponkotuy** [comment]
んー実装コスト高い割にイベントでしか使わないのがつらぽよな事案だ…需要があるのは分かるけど…

**Comment by b-wind** [comment]
いわゆる艦むすあつめの中心がイベントに極度に集中している現状を見ると、イベントの為にゲームやってるといっていい。
難易度設定 も毎イベント確定で実施して来ているので「イベントだから」と言う理由付けは厳しくなって来ていると思う。

ただし、実際の実装難易度（たぶん整合性を保つのが難しい）事を考えると、本件を MyFleetGirls で実装するのはあまり現実的では無いとも思える。

誰か他の人が PR でも出してくれれば検討の余地が出てくるといった感じかな。

**Comment by ponkotuy** [comment]
> イベントに極度に集中している

それはある。ただ実装したものの次のイベントで無い、とかも容易に想像できてつらい。まぁ甲乙丙に限って言うならそれはあんま無さそうだけど。

結局のところ、どこで甲乙丙の情報が受け取れるか、という場所に難易度が依存しますね。DBの拡張が最低限必要なので、PRまで持ってくのは難しいかな

**Comment by ponkotuy** [comment]
んー色々考えたけど甲乙丙のデータ、map_infoにあるのではという予想

**Comment by ttdoda** [comment]
mapinfoに有りました。 [apilist.txt](https://github.com/andanteyk/ElectronicObserver/blob/develop/ElectronicObserver/Other/Information/apilist.txt#L1298)

実際の通信でも確認しました。

**Comment by ponkotuy** [comment]
折角調査してもらったしやってみるかー

**Comment by ponkotuy** [comment]
GitHubのソースコードにリンク張るときはCommitのhashを含めると、見失わずにすむ。これ豆な 
https://github.com/andanteyk/ElectronicObserver/blob/16cbf2795e0e03fd2ae4d9f63baab7eca21244fb/ElectronicObserver/Other/Information/apilist.txt#L1336

**Comment by ponkotuy** [comment]
んあーバックエンドできたけどUIがめんどいぞーだれか案をくれー
