### ISSUE TITLE
艦載機熟練度の対応

### ISSUE THREAD

**Issue by kxbmap** [ponkotuy/MyFleetGirls#273]
以下があればいいかな

- [x] 熟練度の表示
- [x] 艦隊制空値への反映
- [ ] スナップショットに対応

制空値に関しては艦戦の熟練度最大で搭載数に関わらず制空値+25らしい。
中間の熟練度でどうなってるのかは不明。検証も面倒くさそう。

**Comment by ponkotuy** [comment]
制空値への反映だけは優先してやりたいけど、中間の熟練度の情報揃ってからか…。とりま線形にしとくか

**Comment by ponkotuy** [comment]
とりあえず内部データ取得分のリリース。生データが見たい

**Comment by ponkotuy** [comment]
スナップショットはめんどいので一旦close
