### ISSUE TITLE
一部音声ファイルで parse error

### ISSUE THREAD

**Issue by b-wind** [ponkotuy/MyFleetGirls#275]
```
/kcs/sound/kckbdewgsfrkra/10.mp3
fail parseURL: http://125.6.188.25/kcs/sound/kckbdewgsfrkra/10.mp3
/kcsapi/api_req_kaisou/powerup
/kcs/sound/kckbdewgsfrkra/9.mp3
fail parseURL: http://125.6.188.25/kcs/sound/kckbdewgsfrkra/9.mp3
/kcs/sound/kclpiecumljbyp/9.mp3
fail parseURL: http://125.6.188.25/kcs/sound/kclpiecumljbyp/9.mp3
/kcs/sound/kclpiecumljbyp/10.mp3
fail parseURL: http://125.6.188.25/kcs/sound/kclpiecumljbyp/10.mp3
```

**Comment by b-wind** [comment]
該当のリクエスト見る限り、 ?VERSION=  というパラメーターは付いていない模様。

**Comment by ponkotuy** [comment]
MyFleetGirlsのログは?以降省くけど、ブラウザのログもそんなん？

**Comment by b-wind** [comment]
上位に Fiddler 設定して、リクエスト自体直接見てる。

**Comment by ponkotuy** [comment]
であれば付いてないのか…あいつらのAPI設計謎い。VERSION付いてないときに仮につけるVERSIONの設計が必要か？nullable？

**Comment by ponkotuy** [comment]
version付いてるのもあるな。全部外した訳ではなさそう

**Comment by b-wind** [comment]
そのまま表すなら null だろうねぇ。
自分で作ってるやつなら 0 とか -1 とかやりようはあるけど

**Comment by b-wind** [comment]
VERSION クエリ、付いている奴の方が多いっぽいが、付いていない奴もある と言う程度。

**Comment by ponkotuy** [comment]
0とかにすると、versionの高い奴が優先される仕様が邪魔をしそうなので、コンパイルエラーになるnullableが妥当(nullにするのはDB上だけで、Scala上ではもちOption

**Comment by ponkotuy** [comment]
ん、それとも0のときだけversionが外れて次から番号付いてくスタイルか？だとすると厄介過ぎる

**Comment by ponkotuy** [comment]
酒匂と能代か…どっちもまだ音声1つも来てないし、version=0とする方が妥当そう。とりまそれで
