### ISSUE TITLE
'15 夏 E-5 E-7 艦娘ドロップ でマップに誤った画像が表示される

### ISSUE THREAD

**Issue by gaku-hosaka** [ponkotuy/MyFleetGirls#276]
https://myfleet.moe/entire/sta/drop_alpha/31/5
https://myfleet.moe/entire/sta/drop_alpha/31/7

ゲージとかボスの画像が出ちゃってます

**Comment by ponkotuy** [comment]
報告さんくす。直します

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/66dd747e0bf3e449225cdef21ac49739551a1dd6
