### ISSUE TITLE
Flash 送信時のエラー

### ISSUE THREAD

**Issue by b-wind** [ponkotuy/MyFleetGirls#278]
```
/kcs/resources/swf/ships/pbgkfylkbjuy.swf
8 27, 2015 8:26:57 午前 com.ponkotuy.util.Log$class error
ERROR: Error Response 400
HTTP/1.1 400 Bad Request
Wrong Filename or Not Found Master Data
```

実際のリクエスト
http://125.6.188.25/kcs/resources/swf/ships/pbgkfylkbjuy.swf?VERSION=2

バグなのか想定された動作なのか分からないけれど、エラーを返されるのは不可解。

**Comment by ponkotuy** [comment]
気付いてはいたが面倒くさいので放置していた奴シリーズその1だ。やるw

**Comment by ponkotuy** [comment]
んーサーバ側の挙動が正しくてBadRequestを想定に入れてないClientが悪そう

**Comment by ponkotuy** [comment]
masterから敵データが消えたのが根本的な問題か。あんま対処する方法無いなぁ

**Comment by ponkotuy** [comment]
まぁBadRequestからOkに変えるしかないか
