### ISSUE TITLE
小破、中破、大破を表示して欲しい

### ISSUE THREAD

**Issue by k-shin** [ponkotuy/MyFleetGirls#280]
HPの1/4で大破ってのは知ってるけどギリギリだと判断が難しい
艦むす一覧で名前を色分けとかで現在の状況を分けて貰えると有難い

仕事中とかに艦これして「今中破なのか大破なのか解らない！これ進軍して良いの？」って時に色々と捗りそう

**Comment by ponkotuy** [comment]
ちゃんと取れてるか分からんしMyFleetGirlsの情報鵜呑みにするのは非推奨だけど、まぁ簡単に作れそう
