### ISSUE TITLE
イベント難易度別のフィルタが機能していない

### ISSUE THREAD

**Issue by kxbmap** [ponkotuy/MyFleetGirls#284]
![2015-09-06 16 57 45](https://cloud.githubusercontent.com/assets/409709/9703275/28a8bc00-54b9-11e5-93b2-c3bf8877c641.png)

* グラフは直前に表示していたもの
* 下部の一覧は一件も表示されない

**Comment by ponkotuy** [comment]
中身が1件も無いときの表示バグっぽい。
それはそうとちゃんと動いてなくて全部0件なのも確かだ

**Comment by ponkotuy** [comment]
どっちにせよサーバ側はイベント終わってるし分からん。とりまUIだけ直す
