### ISSUE TITLE
Backup体制の改善

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#290]
現状1日1回、mysqldumpでbackupを取っているが、死ぬほど重いしその間応答してないので、もっと近代的に、最低でもbackup中でもQueryを実行できるようにしたい

**Comment by k-shin** [comment]
core数2ならpigz圧縮よりlzoとかの方が早いんじゃないかな？
圧縮率は悪くなるけど


と適当な事を言ってみる

**Comment by ponkotuy** [comment]
いや、mysqldumpでテーブルがロックされるのが問題でな。どっちにせよネックはCPUではなくI/O

**Comment by ponkotuy** [comment]
mysqldumpの引数変えれば改善するだけの話かもしれぬが

**Comment by k-shin** [comment]
--skip-lock-tables --single-transaction とか付けて実行すれば良さそうな感じ？

**Comment by b-wind** [comment]
ARIA ストレージエンジン（ MyISAM ベース ） なので  --single-transaction でロックがかかると思われ。

**Comment by b-wind** [comment]
あれ、逆にトランザクション効かなくて一貫性ないのだっけ、この場合どっちだっけ。

**Comment by k-shin** [comment]
mariadbなのを完全に忘れてた。
MyISAMだとトランザクション対応してないから --single-transaction でも一貫性は保証されない。

tableロックするしか無さそう。

**Comment by ponkotuy** [comment]
何も考えずにARIAストレージエンジンを選んだツケを今支払わされている感…

**Comment by ponkotuy** [comment]
ファイルシステムレベルでバックアップ取った方がいいかな(スナップショット対応のファイルシステム使うとか

**Comment by k-shin** [comment]
物理ファイルのバックアップは良さそうな感じがするけどhddの空きが割りと微妙そうな感じがする

zfsとかで取れないか試してみたけど私の知識じゃ厳しかった

**Comment by ponkotuy** [comment]
よく見たらLVMで作ってあるし余裕でsnapshot取れるのでは、って気がしてきた

**Comment by ponkotuy** [comment]
(どこにコピーするんだよ問題

**Comment by ponkotuy** [comment]
んーこういうときにsakuraだと自由度低過ぎてだめね

**Comment by b-wind** [comment]
別にコピー先はどこぞのクラウドでも自宅マシンでも何とでもすれば良いと思うけど。

**Comment by ponkotuy** [comment]
それいけるのかな？流石にpartitionは区切っておいて、別partitionに保存する、ぐらいの手間は要るかと思うけど

**Comment by b-wind** [comment]
LVM でのスナップショット と言う文脈に従えば、スナップショット取得後はマウント可能なブロックデバイスとして扱えるのだから、適当に rsync なりなんなりでコピーすれば終わり。
http://uc2.h2np.net/index.php/LVM%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E3%82%B9%E3%83%8A%E3%83%83%E3%83%97%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88

もっとも、復元まで考えたバックアップポリシーとしてこれがベターかどうかは判断付けられないけど。

**Comment by b-wind** [comment]
おもなバックアップ手法についてマニュアルに纏まってた。
http://dev.mysql.com/doc/refman/5.6/ja/backup-methods.html

**Comment by ponkotuy** [comment]
mysqlhotcopyを使えば良いのでは、という気がしてきたのでやる

**Comment by ponkotuy** [comment]
ついでにgzから更に高圧縮な形式に変更したい。サイズが馬鹿にならぬ

**Comment by ponkotuy** [comment]
と思ったけどgz以外だと圧縮でCPU食い過ぎるから却下かな…

**Comment by kxbmap** [comment]
> https://dev.mysql.com/doc/refman/5.6/ja/mysqlhotcopy.html
> このユーティリティーは MySQL 5.6.20 で非推奨で、MySQL 5.7 で削除されます。

> https://mariadb.com/kb/en/mariadb/mysqlhotcopy/
> mysqlhotcopy is currently deprecated.

レプリケーション設定してスレーブからバックアップ取るのがいい気がするけどサーバー2台必要である

**Comment by ponkotuy** [comment]
Deprecatedかー。MySQLと違ってMariaDBは特に削除される予定について無いけど。
あとMySQLからmysqlhotcopy削除される理由ってPerlのモジュール依存が激しいからだと思ったけど違うんだろうか。

**Comment by ponkotuy** [comment]
一応家サーバでレプリケーションを取ることはノーコストで可能だけど、インターネット越しになると速度、レイテンシ、通信量でつらみを感じる

**Comment by kxbmap** [comment]
> http://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-20.html
> The mysqlhotcopy utility is now deprecated and will be removed in a future version of MySQL. Among the reasons for this: It works only for the MyISAM and ARCHIVE storage engines; it works on Unix but not Windows. Alternatives include mysqldump and MySQL Enterprise Backup.

InnoDBで使えないからいらないよねってのが大きそう。
技術的に問題がある訳ではないと思うから当座は使っとくってことでもいいかと。

**Comment by ponkotuy** [comment]
http://webcache.googleusercontent.com/search?q=cache:wv3tOiE-ffMJ:www.tocker.ca/2014/04/17/proposal-to-deprecate-mysqlhotcopy.html+&cd=1&hl=ja&ct=clnk&gl=jp
こっちでも読んでみたけど、おっしゃった通りとても条件が限られるのが理由っぽいですね。MyFleetGirlsは珍しく条件満たしてるし問題は無さそう

**Comment by ponkotuy** [comment]
|       | uncompressed | gzip | xz |
|----|------------|----|--|
| Size | 5.1GB | 2.1GB | 1.7GB |
| Compress Time | 0s | 47s | 768s |

**Comment by ponkotuy** [comment]
やっぱgzipですかねえ

**Comment by b-wind** [comment]
http://catchchallenger.first-world.info//wiki/Quick_Benchmark:_Gzip_vs_Bzip2_vs_LZMA_vs_XZ_vs_LZ4_vs_LZO

見る限りどの部分でも最高レベルには無いけれど平均点は高いなぁ。

**Comment by b-wind** [comment]
一応レプリケーションは１台のマシンでも可能だよねと言うのは大きな余談。

**Comment by ponkotuy** [comment]
レプリ1台か…色々足らんそうだな…

**Comment by b-wind** [comment]
あとはまぁ mysqlsnapshot なんてコマンドも有ったよねと言う。

**Comment by ponkotuy** [comment]
それ、AURにも入ってなかったんですけど大丈夫なんですか…

**Comment by b-wind** [comment]
> 一応家サーバでレプリケーションを取ることはノーコストで可能だけど、インターネット越しになると速度、レイテンシ、通信量でつらみを感じる

mysql 標準のレプリケーションは非同期だし速度・レイテンシは別に気にしなくても良いような。
通信量は確かにそれなりにあるけれど。
バックアップの保存場所という意味では考えても良いんじゃ無いかなぁ。

**Comment by ponkotuy** [comment]
通信量大杉でインスタンス止められる可能性ある気がしたんだがどうだろ

**Comment by b-wind** [comment]
mysqlsnapshot 「実践杯パフォーマンス MySQL」の初版にものってる由緒あるツールではある。

**Comment by b-wind** [comment]
差分転送で圧縮もありならそこまで多大なデータ量になるだろうか（中身見てないから知らない）

**Comment by ponkotuy** [comment]
mysqlsnapshot、多分mysqlhotcopyの前身ツールみたいな奴じゃないかなーという気がする。tarに固めるかどうかぐらいの違いしかないしhotcopyで十分かな…

**Comment by ponkotuy** [comment]
転送時に圧縮掛けられるのか。それなら何とかなるかな。試してみるか

**Comment by ponkotuy** [comment]
Slave追加時にちょっと停止が必要だからメンテでやる奴やな

**Comment by ponkotuy** [comment]
レプリケーション時にSSLまで掛けられるのか。強い

**Comment by ponkotuy** [comment]
Slaveで問題なく動いてるので今回はこれでOK。ただし余裕があればSSL設定ぐらいはいつかしたい
