### ISSUE TITLE
テーブル定義でおかしな所

### ISSUE THREAD

**Issue by b-wind** [ponkotuy/MyFleetGirls#297]
- [x] deck_ship に PRIMARY KEY が無い
- [x] ship_history に PRIMARY KEY が無い
- [x] ship_buttle_result に PRIMARY KEY が無い
- [x] remodel_slot に PRIMARY KEY が無い
- [x] snapshot_text だけ InnoDB

**Comment by ponkotuy** [comment]
ship_battle_result…全然知らないtableだと思ったらそもそも使ってない奴や

**Comment by ponkotuy** [comment]
RemodelSlotはuniqueに使えるキーが無いなぁ。どうしたもんか

**Comment by b-wind** [comment]
レコードを一意に特定できるカラムの組みあわせが無いなら、autoincrement なカラム追加してサロゲートキーとして使うかなぁ。

設計的には PRIMARY KEY が無いというのも無くは無いけど、実用上不便になることが多いので。

**Comment by ponkotuy** [comment]
マージは10/30の艦これメンテ中にする(Migrationにおそらく10分掛かる

**Comment by b-wind** [comment]
上手くやれば停止時間殆ど無しでも出来るけど、ミスりそうでアレ。

**Comment by ponkotuy** [comment]
masterとslaveの切り替えでやるんだよ、って教えてもらったことはあるなぁ

**Comment by b-wind** [comment]
そこまでしなくても、

- 変更後の構造の別テーブル作る
- 現テーブルから新テーブルにデータコピー
- 現テーブルと新テーブルを rename で入れ替え。
- 不要になったテーブルを DROP

とかでいい。
細かく言うとコピーから入れ替えの間に発生したデータの差分調整も要るけど。

**Comment by ponkotuy** [comment]
差分調整を自動でやってくれるmaster/slaveが真面目にやるなら良い、という話かもしれない。まぁSlaveにできるマシンはMyFleetGirlsには存在しないのだが。
あと身も蓋もない話をすれば、艦これより優れた保守体制は要らぬw 技術的好奇心はあるけどw

**Comment by b-wind** [comment]
スマヌが何を言っているのかよく分からぬ。

**Comment by b-wind** [comment]
ちなみに新テーブルを作って入れ替えてるの、実は MySQL ( MyISAM ) での ALTER TABLE の実装自体が大体こんな風になってる。

**Comment by ponkotuy** [comment]
あれ…ぼくもあのときの自分が何言ってるか分からない…なんでだろう…

**Comment by ponkotuy** [comment]
マージ済
