### ISSUE TITLE
FinagleProxy.scalaの意味のないコード

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#300]
https://github.com/ponkotuy/MyFleetGirls/pull/299#issuecomment-150499235 で指摘があったコードが実際Immutableアノテーションが付いており意味が無さそうなので修正。

この修正自体は

https://github.com/ponkotuy/MyFleetGirls/commit/90521d8b045826575ed7988516890e68eea88807

で行なわれている。PRは #229 

あまりテストしてない箇所なので、ちゃんと動いてない可能性もある

**Comment by ponkotuy** [comment]
というのでどうでしょう？

**Comment by b-wind** [comment]
これかぁ……
当初使い方分かって無くて、自力で上位プロキシに投げる方向で実装したんだよね。
https://github.com/ponkotuy/MyFleetGirls/commit/1b4e59121171fd248e4d543cc52ade36dac4ab6b

で、その時に戻し忘れてたらしい。

現状意味が無いのはその通りなので該当行をさっくり消してしまうのが妥当かなぁ？

**Comment by b-wind** [comment]
手順的には該当コミット https://github.com/ponkotuy/MyFleetGirls/commit/90521d8b045826575ed7988516890e68eea88807 １つを revert すれば良いはずだけど、Github 的にはどうやるのが良いのだろう。
revert した PR を作る？

**Comment by ponkotuy** [comment]
revertしたPR作ってもいいけど、そこそこ古いしぼくがリファクタかましてるので、素直に修正した方が却って早いかも

**Comment by ponkotuy** [comment]
おわったしcloseしよう
