### ISSUE TITLE
本番系のSlaveサーバを家サーバで動かす

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#302]
#290 のbackup体制変更の1手段。

**Comment by ponkotuy** [comment]
とりま http://wadslab.net/wiki/index.php?MySQL%20%A5%EC%A5%D7%A5%EA%A5%B1%A1%BC%A5%B7%A5%E7%A5%F3%A4%CE%A5%BB%A5%C3%A5%C8%A5%A2%A5%C3%A5%D7%BC%EA%BD%E7 の3まで終わってるので、残りを10/30メンテでやる

**Comment by ponkotuy** [comment]
転送時圧縮は設定済。SSLは面倒そうなのでやめる

**Comment by b-wind** [comment]
うろ覚えだけど経路中での暗号化無いと、Slave からの接続認証関連も plain で筒抜けだと思うけど、そこは良いのかな？

mysql 自身で暗号化しなくても適当な VPN 経由でも良いという話ではあるけど。

**Comment by ponkotuy** [comment]
一応中身が筒抜けになっても問題ないデータの持ち方にはしているつもり。あとslaveが接続に使うアカウントはslaveでしか使えないのにしてある

**Comment by ponkotuy** [comment]
Slave設定は完了。backup体制の再構築(現行のmyfleet.moeでのbackupを廃止してslaveでやるようにする)はまた後日

**Comment by ponkotuy** [comment]
Slaveもうまく動いてるし、myfleet.moeのbackupを停止。slaveでのdumpも確認
