### ISSUE TITLE
戦果を計算する

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#311]
戦果って実は計算できるらしいぞ、始めて知った

https://twitter.com/N_sand2000/status/672104186272571392

https://twitter.com/rion8701/status/672107912571969536
https://twitter.com/rion8701/status/672109071915323392

あたり真面目に実装すれば良いじゃろ。現行戦果という実データもあるからテストも容易

**Comment by ponkotuy** [comment]
Viewは既に戦果グラフあるんだから重ね合わせるのと、別途現在値が欲しいかな

**Comment by ponkotuy** [comment]
艦これ本体と同じように2時と14時に集計バッチ動かして集計するのが良さそうか

**Comment by ponkotuy** [comment]
https://twitter.com/rion8701/status/672115321264693248

**Comment by ponkotuy** [comment]
https://twitter.com/rion8701/status/672119163301662720

**Comment by ponkotuy** [comment]
月末の22時に月次リセット

https://twitter.com/rion8701/status/672119646753951744

**Comment by ponkotuy** [comment]
今年のEOの経験値換算分も戦果に入る

https://twitter.com/rion8701/status/672283024910770176

**Comment by ponkotuy** [comment]
ということはEO1年分を取っておかないと正確な計算できないね。やめとこうという気持ち高まる

**Comment by ttdoda** [comment]
> 「前月度の」EO海域クリアボーナス戦果も引き継ぎに関与していると見られている。

と「前月度の」が強調されているので、EOは前月分のみが引き継ぎ戦果に影響すると思っているのですがどうでしょうか?

**Comment by ponkotuy** [comment]
エエエェェェマジで。なんつか法則性に欠ける感じの実装だなぁ

**Comment by ponkotuy** [comment]
前月のEOぐらいなら結構取れるか

**Comment by ponkotuy** [comment]
とりあえず作ってみてどのぐらい誤差が出るか見てみよう

**Comment by k-shin** [comment]
中の人に聞いてみる？

**Comment by ponkotuy** [comment]
うーん、それは禁じ手な気がするしやめておこうw

**Comment by ponkotuy** [comment]
サクッと作ってみたので、slaveサーバで誤差を調べる https://github.com/ponkotuy/MyFleetGirls/tree/battle-score

**Comment by k-shin** [comment]
検証は任せろ。

**Comment by ponkotuy** [comment]
本番サーバはメモリカツカツなのでやりたくないぞい…

**Comment by ponkotuy** [comment]
作ってみたけどEO計算がゲロ重なのでチューニング要りそう

**Comment by ponkotuy** [comment]
あと1-6の戦果がBOSS戦の有無では確認できてなくて1-6の戦果が加味されてない

**Comment by ponkotuy** [comment]
そもそも論としてゲージ破壊の有無はwin_rankのS, A, Bでは取れない問題があった。今月のEOはマップのクリア有無でチェックした方が良さそう

**Comment by ponkotuy** [comment]
1-6の戦果を加味したらかなり一致度が高まったぞ。これでいこう

**Comment by ponkotuy** [comment]
Speedupのためにindex追加したけどMigrationに合計3分は掛かる予定だぞ!orz

**Comment by ponkotuy** [comment]
View以外作ってデプロイして動作確認する

**Comment by ponkotuy** [comment]
次のバッチは14時なので寝て待つ

**Comment by ponkotuy** [comment]
負荷も確認した方が良さそう。多分かなり重い

**Comment by ponkotuy** [comment]
動作に問題なさそうなのでViewも作ってリリース。大きな問題は発生していない。(細いバグはちょいちょいありそう
