### ISSUE TITLE
Can 海戦 -> 羅針盤履歴 support 連合艦隊, and from start to first node ?

### ISSUE THREAD

**Issue by c933103** [ponkotuy/MyFleetGirls#313]
連合艦隊:
現在:
![image](https://cloud.githubusercontent.com/assets/1525293/11761150/a2db4c48-a0f1-11e5-8a53-00b3d337ff50.png)
願い:
![image](https://cloud.githubusercontent.com/assets/1525293/11761313/5af989d8-a0f8-11e5-8fd6-0ec7134d1f76.png)

from start to first node:
現在:
![image](https://cloud.githubusercontent.com/assets/1525293/11761061/7db90c82-a0ee-11e5-8dff-65e0e97935b1.png)
願い:
![image](https://cloud.githubusercontent.com/assets/1525293/11761108/121ffd44-a0f0-11e5-9fb1-5bf94bbab4f5.png)

**Comment by ponkotuy** [comment]
from start to first node: #90
