### ISSUE TITLE
新イベント海域のマップ表示

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#322]
https://twitter.com/ttdoda/status/697620890649960448

なんかファイル名が変わったらしい。マンドクセ

**Comment by ponkotuy** [comment]
変わったのは新海域だけらしいですよ奥さん。何で変えたし

**Comment by ponkotuy** [comment]
難読化されている。ぶっこ抜き対策かな

**Comment by ponkotuy** [comment]
難読化名がどこに書かれているか探す必要がありますね

**Comment by ponkotuy** [comment]
本命と思われるapi_start2にないぞ。こまった

**Comment by ponkotuy** [comment]
api_req_map/startとかもないな…

**Comment by ponkotuy** [comment]
E-1は `/kcs/resources/swf/map/gmlbign_zjwmq.swf` だった

**Comment by ponkotuy** [comment]
情報求む状態にしてpendingかな…うーん…ちょっと忙しい…

**Comment by ponkotuy** [comment]
選んだステージを記憶しておいて、なんかのswf/map/hoge.swf読んだらそこのステージと紐付けるという実装を思い付いた。特に情報がなければそれで(ただし極まれに間違える可能性がある

**Comment by ttdoda** [comment]
E-2: `/kcs/resources/swf/map/fgyvwqymk_ekn.swf`
E-3: `/kcs/resources/swf/map/fwy_wlrdttcoc.swf`
でした。

**Comment by ponkotuy** [comment]
_の位置すら規則性が無いですね…なぞ

**Comment by ttdoda** [comment]
ID331の天城の画像が`gmlbignzjwmq.swf`で33-1のマップが`gmlbign_zjwmq.swf`、
ID332の葛城の画像が`fgyvwqymkekn.swf`で33-2のマップが`fgyvwqymk_ekn.swf`と
なんらかの法則が有りそうなんですけれどね。_の位置が謎ですが。

**Comment by ttdoda** [comment]
自分もどこかに情報がないか探してみたのですが見当たらなかったので、
記憶しておいたステージと紐付ける方法でいいと思います。
最初の一人で間違えなければいいだけですし、間違いが発覚したら消して再度送って貰えばすむでしょうし。

**Comment by ponkotuy** [comment]
Hashっぽいなぁw まぁ記憶しておいたステージと紐付ける方法でいきましょう

**Comment by ttdoda** [comment]
春イベントが近いですが状況はどうでしょうか?

**Comment by ponkotuy** [comment]
ウッ、今度こそ…!

**Comment by ttdoda** [comment]
また命名規則を変えたのか、'16春E1が lddsvnlihrvtnpjkwqcelxpsmylpcqcyifty.swf と妙に長くなってますね

**Comment by ponkotuy** [comment]
意味のないことを…
