### ISSUE TITLE
新呉鎮守府のIPアドレス

### ISSUE THREAD

**Issue by ttdoda** [ponkotuy/MyFleetGirls#324]
疎開で呉鎮守府のIPアドレスが変わったようです。
新しいIPアドレスは 203.104.209.87 らしいです。

http://blog.ishotihadus.com/?p=43
http://203.104.209.7/gadget/js/kcs_const.js

**Comment by ponkotuy** [comment]
ありがとうございます、やりませう

**Comment by ponkotuy** [comment]
ref付け忘れた https://github.com/ponkotuy/MyFleetGirls/commit/bcd63e56342ea077d0c63cc3705fcbc2061195cb

**Comment by ponkotuy** [comment]
速攻デプロイじゃー

**Comment by ponkotuy** [comment]
した。動作確認してくれる人募集中

**Comment by ponkotuy** [comment]
してもらった。だいじょうぶだとおもう
