### ISSUE TITLE
スナップショットで主砲に艦載機熟練度が付く

### ISSUE THREAD

**Issue by yreeen** [ponkotuy/MyFleetGirls#326]
艦隊スナップショットを撮った時に、3スロ目の水偵に付いている艦載機熟練度が
2スロ目の主砲に付与されてしまう現象を発見したので、報告させて頂きます。

画像は[こちら](https://pbs.twimg.com/media/CbdrexcUEAEVPEU.png:large)です。
おかしくなっているスナップショットは[こちら](https://myfleet.moe/user/748405/snapshot)です。

**Comment by ponkotuy** [comment]
観測機とズレてる事案ですね…適当実装したのがバレてしまう事案だ

**Comment by ponkotuy** [comment]
直ったぞい!(ぶっつけ本番だった
