### ISSUE TITLE
装備情報が取れない

### ISSUE THREAD

**Issue by ttdoda** [ponkotuy/MyFleetGirls#330]
装備情報が反映されないという[tweet](https://twitter.com/pulo_jpp/status/716971618996609024)あり。
[該当ユーザの装備情報ページ](https://myfleet.moe/user/13013063/slotitem)を見ると、確かに取れていない。

4/1のメンテでAPIが一部変わったらしいので、その影響かも。
[KancolleSnifferの修正内容](https://osdn.jp/projects/kancollesniffer/scm/git/KancolleSniffer/commits/4bd3b264eba68b5ef16802f74e7664b0cdcd565d)を見ると、api_get_member/require_infoが新設され、
api_get_member/slot_item, api_get_member/kdock の情報が新設されたAPIに移った模様。

**Comment by fujieda** [comment]
反映されないのは一度も出撃してないからですね。ログイン時のリクエストがrequire_infoにまとめられただけで、出撃して帰ってくればslot_itemは飛びますから。初めてのユーザーが戸惑うことがないよう、require_infoに対応しておいた方がいいとは思いますけど。

**Comment by ponkotuy** [comment]
ふうむ、対応します
