### ISSUE TITLE
Enable HTTPS to MFGs proxy

### ISSUE THREAD

**Issue by slime7** [ponkotuy/MyFleetGirls#332]
自己写了个获取游戏地址的网页，登录页面需要先关闭mfg的代理，很麻烦

**Comment by ponkotuy** [comment]
In English or Japanese, please.

**Comment by slime7** [comment]
中國にDMMをログインしないから、私は[そんなもの](https://github.com/slime7/dmmlogin)を作れた。てもMyFleetGirlsはhttpsをプロキシーません。

**Comment by ponkotuy** [comment]
I see, but I don't know how to do. I welcome pull request.

**Comment by kxbmap** [comment]
We should implement `CONNECT` handling  if provides HTTPS support.

See:
* https://tools.ietf.org/html/rfc2817
* https://www.ipa.go.jp/security/rfc/RFC2817JA.html (Japanese)
