### ISSUE TITLE
'16春イベントのマップが正しく表示されない

### ISSUE THREAD

**Issue by ttdoda** [ponkotuy/MyFleetGirls#334]
海域情報で'16春イベントのマップの内いくつかがマス目等が表示されず、背景のみになっています。

問題が出ているマップ: E4, E5, E7

**Comment by ponkotuy** [comment]
オッ、swfの解析ミスってますね。海域のswfファイルが必要なので、だれかURLかswfファイルそのものを下さい…

**Comment by ttdoda** [comment]
E4: /kcs/resources/swf/map/wxjwlfrhgcklfdsibozycoxusitdrbcvspjm.swf
E5: /kcs/resources/swf/map/ttiowoxbvxkzupqukiogqbferupdilhnbuss.swf

**Comment by ponkotuy** [comment]
さんくす。あとで試します

**Comment by ponkotuy** [comment]
ギミックのせいで背景を差し替える処理をしているみたいですね。
ということは自前で合成しないといけない…マジか…？
