### ISSUE TITLE
Duplicate Ranking

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#341]
初期艦ランキングで艦娘が複数表示されたりする

**Comment by kxbmap** [comment]
初期艦だけじゃなくて他のランキングもおかしいように見える。

例えば資源ランキング1位の人が12位にも表示されている
https://myfleet.moe/entire/sta/ranking/Admiral#detail=MaterialRanking

**Comment by ponkotuy** [comment]
「たり」の範囲が異常に広いというだけですw
DBに複数データ入ってるしCronまわりのバグですね、はーPlayのDIきらい

**Comment by ponkotuy** [comment]
(UNIQUE KEYを設定してない奴が悪い説の方が支配的である

**Comment by ponkotuy** [comment]
そういえば最近Actorが重複起動して困る問題があって、MFGCronオブジェクトが2つ存在している可能性がある

**Comment by ponkotuy** [comment]
デプロイして確認中

**Comment by ponkotuy** [comment]
何回か再起動して再発してないから問題なさそう
