### ISSUE TITLE
艦載機熟練度による制空値計算の修正

### ISSUE THREAD

**Issue by kxbmap** [ponkotuy/MyFleetGirls#364]
現状の計算は熟練度実装初期に仮に実装したものなので、最新の情報を元に修正する。

Wiki (http://wikiwiki.jp/kancolle/?%B4%CF%BA%DC%B5%A1%BD%CF%CE%FD%C5%D9) によると、計算式は以下。

```
上昇制空値＝内部熟練ボーナス＋制空ボーナス(艦戦・水戦/水爆)
内部熟練ボーナス＝√(内部熟練度/10)
```

内部熟練度に幅があるけど、最小値で計算するのがいいかな

**Comment by ponkotuy** [comment]
:+1: 最小値で計算するで良いと思う
