### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by silfumus** [ponkotuy/MyFleetGirls#367]
I have been having problem playing KanColle with MyFleetGirls.

KanColle would occasionally have long loading times and finally gives me catbomb whenever I was clicking around in homeport/HQ. Yet it hasn't happened even once when I was doing sorties.

To get around that problem, I usually unchecked the proxy settings in Internet Options and shut down MFG. After a moment, KanColle will cease loading and do whatever it was supposed to do without giving me catbomb.

I've tried multiple viewers and the problem persist. The only time I didn't have the problem was when I play KanColle without MFG, it plays fine without any catbomb whatsoever.

Partial log: http://pastebin.com/5f32sbw1

Because of that, I only turned on MFG whenever I want to post routine senka data, etc.

**Comment by b-wind** [comment]
@silfumus  Please use mfg ver 1.5.14 or later. We updated network library, so stability has improved.
