### ISSUE TITLE
クライアントがだす各種メッセージを Logging Framework を利用するようにしたい。

### ISSUE THREAD

**Issue by b-wind** [ponkotuy/MyFleetGirls#374]
現状 MyFleetGirls Client の出すメッセージが STDOUT のみに出力されている。
これを SLF4J 経由にしたい。
理由として、以下が上げられる

- ログメッセージの一種で有り統一的に扱いたい
- application.log にも残したい

作業的には println しているクラスで Log トレイトを追加（元々有る物も多い）
println を logger.info() or logger.err() など、適切な物に変更する。

**Comment by k-shin** [comment]
序と言っては何だけどapplication.confで出力するlogのLogLevelが設定出来ると有難い。

**Comment by b-wind** [comment]
どっちかと言うと出力 LogLevel の調整は [logback.xml](https://github.com/ponkotuy/MyFleetGirls/blob/master/client/src/main/resources/logback.xml) をカスタマイズしてクラスパスの先頭に置く（と同梱の物より優先して読み込まれる）のが正攻法かと。
書式がメンドウクサイとかそう言うのはあるけど。

**Comment by b-wind** [comment]
一応このPRですべての出力が SLF4J + logback 経由で出る…… はず。

**Comment by ponkotuy** [comment]
ぼくもapplication.confではなくlogback.xml派かなー。

**Comment by ponkotuy** [comment]
ただprintlnしてるやつってログではないからprintlnしてるのであって、それをログにするモチベは良く分からない。ログとしても欲しい奴は両方で出力するように変更した筈

**Comment by ponkotuy** [comment]
従ってログメッセージだと思っていないというのが回答になる

**Comment by b-wind** [comment]
ではそれらはなんの為に出力されているの？

**Comment by kxbmap** [comment]
ユーザーインターフェースかと。
MFGがリッチなクライアントになるとしたらGUIに置き換えられる部分ということで、自分もログではないと考えてる。
物によってはapplication.logに残したいというのは分かるので、現状で足りないならログ出力を足すのがいいと思う。

**Comment by kxbmap** [comment]
(別の話として、printlnしてる場所が散らばってて各処理と密結合してるのは問題だと思ってる)

**Comment by kxbmap** [comment]
それとlogback.xmlをカスタマイズした場合、JVMの起動引数(`-Dlogback.configurationFile=...`)で指定するのが常道かと。

**Comment by b-wind** [comment]
> -Dlogback.configurationFile=$logbackFilename
なるほど、こんなオプションが。
今のところ各エンドユーザーが切り替えるって事も無いだろうし、どこかに記しておく程度で良いのかなぁ、これは。

**Comment by b-wind** [comment]
logback.xml の書き方相談等は Gitter に言ってくれれば。

**Comment by b-wind** [comment]
それぞれ適用するかどうかは別として、これで思いつく項目はすべてかな。たぶん。

**Comment by ponkotuy** [comment]
ところでlog4jをslf4jに切り替えるモチベはなんだろうか？

**Comment by ponkotuy** [comment]
なんとなく理解した

**Comment by ponkotuy** [comment]
とりあえずこれ終わってるからcloseしていいかな？ @b-wind

**Comment by b-wind** [comment]
言いたい事はあるが、今後別の形で主張するとしようかねぇ。
この Issue の目的設定にはそぐわないし。
