### ISSUE TITLE
おやっ、IOExceptionです！

### ISSUE THREAD

**Issue by Misaka00357** [ponkotuy/MyFleetGirls#397]
Hello,

I try to open the software and it shows this.
![qq 20170120174945](https://cloud.githubusercontent.com/assets/25252804/22160605/93909088-df46-11e6-8f4f-2255be5c6874.png)
I need help and thaks very much.

**Comment by ponkotuy** [comment]
Perhaps you have deleted the necessary update.properties file. I recommend reinstalling.
