### ISSUE TITLE
入手経路検索の日付=が対象になってない

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#407]
少なくともend dateが<になってるっぽ（未確認

**Comment by ttdoda** [comment]
ソースを確認していないので妄想レベルなのですが、2017-09-01 ～ 2017-09-19 と指定した時は
実際には 2017-09-01 00:00:00 ～ 2017-09-19 00:00:00 として扱われていないでしょうか。

**Comment by b-wind** [comment]
この辺の予感。
https://github.com/ponkotuy/MyFleetGirls/blob/1d7cba29a15f6a201082283c6b09396713d2f206/server/app/models/query/Period.scala#L30

**Comment by ponkotuy** [comment]
言うとおりですね直します
