### ISSUE TITLE
秘書艦の画像のスケールが大きい

### ISSUE THREAD

**Issue by Nishisonic** [ponkotuy/MyFleetGirls#412]
![image](https://user-images.githubusercontent.com/12210425/29360463-f2b9328e-82bd-11e7-86ae-f537adcc3773.png)

秘書艦の画像のスケールだけ明らかに大きいので、修正お願いします。

**Comment by ponkotuy** [comment]
ちらっと見てみましたが原因は秘書艦ではないですね。伊14がわるいのかな

**Comment by ponkotuy** [comment]
伊14改の画像だけがデカいらしい。んなアホな

**Comment by ttdoda** [comment]
確かに伊14改のみアップロードされている画像が大きいですね。
試しに今艦これサーバからダウンロードした画像を確認しましたが、通常のサイズでした。
伊14改の画像を消して最アップロードして貰うのがよさそうですね。

**Comment by ponkotuy** [comment]
サンクス! やってみるます

**Comment by ponkotuy** [comment]
なおった。閉じます
