### ISSUE TITLE
Saratoga Mk.IIが登録されていない

### ISSUE THREAD

**Issue by kema8351** [ponkotuy/MyFleetGirls#415]
9/12のメンテで実装されたSaratoga Mk.IIとSaratoga Mk.II Mod.2が
MyFleetGirlsに登録されていないようです。
自艦隊のSaratoga Mk.IIが艦娘一覧に表示されず、Statisticsの艦娘図鑑にも登録されていません。

原因はクライアント側がapi_start2のレスポンスを送れないことのように見えます。
api_start2を叩いた後にクライアント側でエラーが発生しています。

エラーはMasterShipの解析中に起きているようです。（MasterShip.scalaの58行目）
現在のapi_start2レスポンスではid788～799にapi_sortnoを持たない艦娘データが存在します。
（9/12のメンテで使われなくなった夏グラフィック関連のデータのようです）
このデータが56行目のShipIds.isEnemyを素通りしてエラーを起こしているように見えます。

エラーログ・ソース・Jsonレスポンスからの推測なので別の原因かもしれません。
以上、バグの報告でした。対応をよろしくお願いします。

**Comment by ponkotuy** [comment]
isEnemyはその名の通り鑑娘は素通りしてくれないと困るので、公式の図鑑(順序をsortnoで定義している)がどのように処理しているのか調査する必要がありますね…

**Comment by ponkotuy** [comment]
sortnoの無い艦娘を処理する仕組みはMyFleetGirlsサーバ側に存在しないので、client側で勝手にidを補完という雑な解決方法で処理…でいいかとりあえず

**Comment by ponkotuy** [comment]
勘違いしていた。そもid788以降は艦娘として処理するのは難しいデータですね

**Comment by ponkotuy** [comment]
送信しないようにして修正済

**Comment by b-wind** [comment]
https://github.com/ponkotuy/MyFleetGirls/commit/c1b4c1f82e970beec4043bd34e83cace4902154e
この変更かな？

**Comment by ponkotuy** [comment]
YES
