### ISSUE TITLE
Docker対応

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#61]
おもしろそう

**Comment by ponkotuy** [comment]
Playを動かすところまではできたけど、MariaDBまわりがうまくいかね

https://github.com/ponkotuy/MyFleetGirls/commit/f307bb2ac8981123c359c9b02e3f129e5baa50a0
https://github.com/ponkotuy/MyFleetGirls/commit/238601c9f090dbf33f9926d86e1f6e51ab9f32a3
https://github.com/ponkotuy/MyFleetGirls/commit/4d29b5e1b8e48ee0c80d487ebff3fac8e1cf8269

**Comment by ponkotuy** [comment]
最終的にどのような形にしたいのか見えてないのがいけない気がしている

**Comment by ponkotuy** [comment]
https://github.com/dokku-alt/dokku-alt 会社で勧められた。これ試そう

**Comment by ponkotuy** [comment]
あとMariaDBはホストの奴にアクセスした方が楽という話だったので、そういう風に書き換えよう

**Comment by ponkotuy** [comment]
MariaDBはホストの方がいいと言ったな。アレは本当だがやめだ。

とりあえず開発環境を主眼に作ってみた。figを使ってMariaDB用インスタンスとPlay用インスタンス分けて、linkしてある。

https://github.com/ponkotuy/MyFleetGirls/commit/ec6d846d65d5849f8c62e1d8d73117da1a1f1586
https://github.com/ponkotuy/MyFleetGirls/commit/6c0114fc541398474989083a63e296b4f9ef9181

**Comment by b-wind** [comment]
いろいろ見ている限り、Nginx 実行コンテナ・Scala ビルドコンテナ・前２つで共用の volume 用コンテナに分けるのが良さそうに見える。

**Comment by ponkotuy** [comment]
volume用コンテナやっぱ要るんですかね…
ところで本番と開発環境で欲しいものが違うからどうしたもんかなーとは思ってるんだけど

**Comment by b-wind** [comment]
欲しい物とは？

**Comment by ponkotuy** [comment]
発表に向けて急ごうと思ったけどその必要が無くなったのでpending

**Comment by ponkotuy** [comment]
技術的好奇心は満足したしcloseしちゃう
