### ISSUE TITLE
Finagle再検討

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#63]
Finagleでproxyできるけど、jarがでかくなり過ぎる問題とか、Scala verupの障害になったりするので、別のを検討する。

Netty、Spray、Colossasとか候補にある

**Comment by ponkotuy** [comment]
絶対パスのまま、という意味

**Comment by b-wind** [comment]
絶対パスのままとは例えば
http://myfleet.moe/path/to/api
てこと？

**Comment by ponkotuy** [comment]
NettyのProxyサンプルとFinagleのサンプルだとGET http://myfleet.moe/path/to で流れてくるんだよね。なんでだろう

**Comment by b-wind** [comment]
それは Proxy に対するリクエストと Proxy から Web サーバーに投げるリクエストは別物だから。
これの図 4-2
http://itpro.nikkeibp.co.jp/article/COLUMN/20071102/286318/

**Comment by ponkotuy** [comment]
なるほど了解しました、GETも削るようにします

**Comment by ponkotuy** [comment]
issue立てた https://github.com/ponkotuy/MyFleetGirls/issues/74

**Comment by ponkotuy** [comment]
Sprayとかレイテンシ少ないし良いのではないか。Actorだし

**Comment by ponkotuy** [comment]
Kernel/VMでこのネタやる予定。あんまライブラリ使わずに素で実装した方がサイズ的に良いのでは、という気がしてきている

**Comment by ponkotuy** [comment]
LittleProxy試して、Finagleの置き換えに8割方成功したので多分いける。ただしJarのサイズが40MB→37MBとかしょっぱいので、本来の目的であるjarのファイルサイズ削るには向いてなさそう。一旦閉じます
