### ISSUE TITLE
艦娘図鑑登録＆装備図鑑 の未所持表示

### ISSUE THREAD

**Issue by b-wind** [ponkotuy/MyFleetGirls#65]
良くも悪くもコンスタントにプレイしていると半数以上の艦は揃うようになってきている
＆大抵の新艦娘・装備もほぼ Twitter 等でリークされる現状を踏まえると
現状の「図鑑に登録されているデータ」を表示するのに加えて
マスターデータには有るが登録の無い艦・装備を表示した方が良いのでは無いか。

艦名・武器名に関しては一応非表示で No のみで良いと思う。
（他人のを見ればほぼ分かるけどそこは Twitter とかで流れてきても実質同じ）

**Comment by ponkotuy** [comment]
v1.2.7割とでかい修正多いのでv1.2.8にまわしー

**Comment by ponkotuy** [comment]
S那珂だけかと思ったらXmasとか正月とか一杯増えたしどうしたもんか

**Comment by ponkotuy** [comment]
艦娘常にコンプしてる人いるしunique取ればいいやという結論になった

**Comment by ponkotuy** [comment]
うりゃ https://github.com/ponkotuy/MyFleetGirls/commit/3057c9d975155a0bb1a0c10304bfe864c7ac5d19

**Comment by b-wind** [comment]
素直な疑問として Xmas ＆ 正月シリーズはマスターデータと図鑑データの対応はどうなってるのか
（図鑑登録された後は対応とれるなら良いけど、龍驤・龍驤改の図鑑データとか見ると無理なんだろうなとか
艦娘はいいけど、装備はコンプされてるのか（初期のランキング報酬でしかまだ出てないとか有るらしいけど）よく分からない部分があるね。
