### ISSUE TITLE
装備改修の曜日毎の表示

### ISSUE THREAD

**Issue by b-wind** [ponkotuy/MyFleetGirls#66]
要はこれ、なのだけどそのままではあまり面白くないし意味も無い。
http://wikiwiki.jp/kancolle/?%B2%FE%BD%A4%B9%A9%BE%B3#week

直近１ヶ月程度の範囲で、曜日毎に改修されている装備のランキングを表示してみるのはどうか？
以下に示す４装備は２番艦に依存しないので装備毎のカウント、
他の装備は二番艦と装備の組みあわせでカウント。

* 12.7cm連装砲（毎日）
* 14cm単装砲（毎日）
* 61cm四連装魚雷（日・月・火・金・土）
* 九四式爆雷投射機（水・木）

**Comment by ponkotuy** [comment]
1.2.11の目玉機能にするかー

**Comment by ponkotuy** [comment]
改修資材が枯渇して失敗時のreponseが取れないwww

**Comment by ponkotuy** [comment]
教えてもらった。 https://gist.github.com/fujieda/cbe0e098f33696f6e923 頑張る必要ないかも

**Comment by ponkotuy** [comment]
JSONのパース書いた。真面目にテスト書いたりした！ https://github.com/ponkotuy/MyFleetGirls/commit/295f83173df49c5c4f8953ef3566b5f3f1fdb52d

**Comment by ponkotuy** [comment]
アッ、POSTのcertainだけは取得した方が良いわ…

**Comment by ponkotuy** [comment]
certainとか諸々追加してとりあえずサーバの蓄積はできるようになった https://github.com/ponkotuy/MyFleetGirls/commit/14824aa41fd8fa933e7b0a4c92910cec64ebeb26

**Comment by ponkotuy** [comment]
ViewはとりあえずVer1.2.11リリース後でいいや

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/issues/101
