### ISSUE TITLE
About ページを Github Pages （等）に移す

### ISSUE THREAD

**Issue by b-wind** [ponkotuy/MyFleetGirls#67]
改訂を繰り返して、大分情報としてはまとまってきているけど、もう少し情報を足した方が良い部分もある。
  https://myfleet.moe/entire/about
その際、プログラム自体のリリースと同時なのは少し面倒かなと。
ついでに Markdown 等その他の記法に（結果としてだけど）対応する辺りは嬉しいかも。

デザイン統一出来るかどうかはちょっと疑問。

**Comment by ponkotuy** [comment]
GitHub Page作ってみたんだよね https://ponkotuy.github.io/aegiscode/ 当然Play使えないからそこそこの書き換えがいるなー

**Comment by ponkotuy** [comment]
正直これはPullRequestに期待しよう

**Comment by b-wind** [comment]
この場合、 GitHub Page の運用については以下のページのケース 2.2 か 2.4 に該当すると思う。
http://tokkono.cute.coocan.jp/blog/slow/index.php/programming/github-pages-workflow/
個人的には 2.4 の運用形態がより適切と思うけどどうかな。

**Comment by xuwei-k** [comment]
playからの書き換えが面倒なら、herokuとかでplay動かすという手も？

**Comment by ponkotuy** [comment]
確かにHerokuが一番手間掛からんそう。とはいえ別プロジェクトとして分離するためには結構いじらないといけないかも。
GitHubページ向けに単純なHTMLにしておくと、Play知らんくても書けてPR貰える率が上がるという話もあり、それはそれで魅力的。
ただ自分でHTMLに変換する気力も時間もないので、俺がやるぜ！って名乗り上げる人がいないなら自動的にHerokuになるなw

まずはHeroku調査か

**Comment by ponkotuy** [comment]
Heroku調査の視点

* ドメイン使えるか
* 料金（無料なら無料の範囲は

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/myfleet_web 作ってみたけど、300MBの容量オーバーして怒られた。対策を考え中

**Comment by xuwei-k** [comment]
容量の問題は、これ

- https://github.com/xuwei-k/myfleet_web/commit/cd9ffc28f0c9113a
- http://d.hatena.ne.jp/xuwei/20140928/1411887455

でいけるはず

**Comment by xuwei-k** [comment]
テスト用というか、使ってなかった自分のやつに試しにデプロイしたら、一応動いた

http://xuwei-k.herokuapp.com/entire/about

**Comment by ponkotuy** [comment]
ありがとうございます！マージさせてもらいました

**Comment by ponkotuy** [comment]
完了
