### ISSUE TITLE
震電改が未所持として表示されない問題

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#81]
みんな持ってないのかよ、ザコめ…うわーなにをするやめろー！

**Comment by k-shin** [comment]
艦隊司令部施設も表示されてないぞ。

**Comment by b-wind** [comment]
艦隊司令部施設 はいくつかのユーザーで見る限り図鑑 No.107 として表示されていますし、
バグがあったとしても本件とは別の問題かなと。

**Comment by k-shin** [comment]
図鑑開いたら反映されました。
何らかの要因（データ更新失敗等？）で私の艦隊司令部施設だけ未所持のままになってたみたいです。

**Comment by b-wind** [comment]
補足。
装備「震電改」は MyFleetGirls 利用者で所持している提督が存在していない（と思われる）為、
#65 で定めた仕様では表示されない事を課題としている。

**Comment by ponkotuy** [comment]
補足Thanks。
色々仕様を考えたけど、masterから未登場なものを除外する形で実装する。それが処理として一番軽い

**Comment by ponkotuy** [comment]
簡単だじぇー https://github.com/ponkotuy/MyFleetGirls/commit/eef5403f02090569e2fa2a3858a27ac896469fe5
