### ISSUE TITLE
Gatlingを試す

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#82]
面白そう。

とりあえず
* 負荷テスト
* APIに対するテスト
という2つの用途で使えそう。

2つの用途で使えるかどうかの確認をする

**Comment by ponkotuy** [comment]
直近で欲しいのは本番環境・テスト環境に対して、APIの網羅的な動作テストする奴欲しいんだよな

**Comment by ponkotuy** [comment]
というのもリリース後に発覚する瑣末なバグ多過ぎ

**Comment by b-wind** [comment]
Selenium じゃダメなん？

**Comment by ponkotuy** [comment]
検討したが、そもそもAPIの網羅的なテストという点では、SeleniumもGatlingも大袈裟で、実際JavaScriptだけで充分なんだよね。ただし一方でCORS制約がキツいし回避めんどうそうなので、サーバサイドで叩く必要があるので、結局Webアプリっぽくなる

**Comment by ponkotuy** [comment]
んんー直近でガトリング欲しい事情無いし一旦閉じる
