### ISSUE TITLE
図鑑に改二改とか改改とか出てくる

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#86]
正月のイラスト分だと思うけど見た目変えるか削除するかした方が良さげ

**Comment by b-wind** [comment]
Xmas / 年末 / 正月分と言うのは確認済み。
そう言う仕様だからそのままにしておくのかと思ってたｗ

**Comment by ponkotuy** [comment]
なるほど。まぁ見た目ぐらいは変えようかなぁという

**Comment by ponkotuy** [comment]
と思ったけどこれクライアント側で処理してる部分だから、ほぼ無理っぽいな。頑張るメリットもそんなないし諦めよう
