### ISSUE TITLE
proxy.pacのキャッシュ期間を変更する

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#92]
現状1時間らしいので3時間に延長する。これでいける

https://www.playframework.com/documentation/ja/2.3.x/Assets

**Comment by b-wind** [comment]
直接関係ないけど、他のファイルはむしろもっと長めでも。と言っても精々半日までだけど。

**Comment by ponkotuy** [comment]
Playに標準設定変える方法無いんだよなー。ショボいしPlayにPR出すカナー

**Comment by ponkotuy** [comment]
嘘だった。あった http://qiita.com/ponkotuy/items/25016925fc994a1c8c51

**Comment by ponkotuy** [comment]
とりあえずproxy.pacの設定変更 https://github.com/ponkotuy/MyFleetGirls/commit/107e74a80f53aa2633296359e0b004cdbc4c0f4e

**Comment by ponkotuy** [comment]
他のファイル、Deployで比較的頻繁に更新されるJavaScriptが含まれているので、半日は長過ぎるんじゃなかろうか

**Comment by ponkotuy** [comment]
ちゃんと制御したい気もするが、設定ファイルにゴリゴリ書くのもショボいので今日はこのぐらいにしといてやろう（やるならOriginalなAssetsを定義した方が良さげ
