### ISSUE TITLE
正月・Xmasの中破絵が出ない

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#94]
仕様上どうしてもやりづらいから放置していたが指摘されたので上げておく。

なにがめんどうかというと、swfの仕様の問題で、通常艦娘の画像はID5が画像、ID7が中破画像になってる。
一方で、Xmasと正月版の艦娘は、ID1が画像、ID3が中破画像になってる。
そして通常艦娘と正月艦娘を区別する方法が、多分無い。

さて、現行仕様はどうなってるかというと、全ての艦娘が5/7でアクセスするようになっている。
で、5or7に画像が存在しなかった場合は1を返す仕様になってる。

従って、5と7と1は返せるけど3が返せないというのが現状の仕様である。

**Comment by b-wind** [comment]
仕様としてしまっても構わない部分だとは思う。
そんなに頻繁に見る物でも無いし、レア艦でもないのでたいていの人は自分の図鑑で見れるはずだし。

**Comment by b-wind** [comment]
一覧の艦名がマスターデータに有る物なら、雑に 艦名の前方一致で判断しても良さそうな気が。

**Comment by ponkotuy** [comment]
一応IDで区別できるようだ。900番以降になってる。S那珂が消えたのも併せて考えると割とこの区分は信用できるのではないか

**Comment by ponkotuy** [comment]
とはいえぼくがソシャゲ開発の現場だったら、IDで判断するコード見つけたらクソコード扱いにするけどね

**Comment by ponkotuy** [comment]
修正した。URLの維持とか併せると若干面倒なことになってる https://github.com/ponkotuy/MyFleetGirls/commit/12e29887821b877c5afdb359e588cacc10b30fba
