### ISSUE TITLE
サーバ監視したい

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#96]
サーバ落ちたときにアラート飛んでくる仕組みは、個人のサービスレベルでもそろそろ必須なんじゃないかと思うわけですよ。

と思ってたらMackerelを勧められたんだよね https://mackerel.io/

**Comment by ponkotuy** [comment]
お試しでデスクトップ入れてみたけど良い感じだ。Freeのアカウントでも無問題だし早速本番に入れよう

**Comment by ponkotuy** [comment]
できた。落ちたらアラート飛ぶか試した方が良さそう

**Comment by ponkotuy** [comment]
初期設定だとメールしか飛ばないので、気付きにくいと思われる。ので、色々調査してみた。

Webhookというオープンな仕様のpush通知の仕組みをMackerelが使えるので試してみたが、そもそもWebhookに対応するサービスが少ない。少ないものの1つであるZapierを試してみて、良さそうだと思ったが、転送先設定が微妙だった。

* Notify My Androidは20分前後遅れる
* Twitterは公開で自分がTweetする（せめてBOTからのreplyかDMにしてほしい）
* XMPPはそもそもim.kayac.comの方が楽そう

というのでim.kayac.comでGMailアカウントに転送するようにした。

**Comment by ponkotuy** [comment]
Hostの初期設定は状態がStandbyになっており、Workingに変更しないとアラート飛ばない。結構分かり辛い

**Comment by b-wind** [comment]
通知は PushBullet がよいと思う。

**Comment by ponkotuy** [comment]
完成してテスト終わったタイミングで言いますかw まぁ一応調べてみます

**Comment by b-wind** [comment]
ネタバレ除けにしばらく Twitter も閉じていたのだから仕方ないね？

**Comment by ponkotuy** [comment]
PushBulletに通知させるためにMackerelとの間にもう1枚サービス噛まないといけないし面倒だから見なかったことに。とりあえず一つの媒体で応答すれば全部消えるという仕組みは結構欲しかったけど

**Comment by b-wind** [comment]
Zapier -> PushBullet は有るはずだけど。

**Comment by ponkotuy** [comment]
im.kayac.comに比べて噛む外部サービスの数が1枚増えるのを敬遠した
