### ISSUE TITLE
複数の嫁艦

### ISSUE THREAD

**Issue by ponkotuy** [ponkotuy/MyFleetGirls#97]
公式だって重婚認めているんだから嫁艦が複数隻あってもいいじゃない

**Comment by b-wind** [comment]
嫁という地位に固執しないという考え方も有る。

**Comment by ponkotuy** [comment]
突然名称変わったら混乱するだろうから嫁1234とかになりそう

**Comment by ponkotuy** [comment]
内部的には嫁の数に上限は置かないけど、表示の都合で4人までにするのが適切かなぁと感じている

**Comment by edochan** [comment]
嫁登録した子のなかから無作為で誰か一人表示されるとか

**Comment by ponkotuy** [comment]
その方が実装は楽だけれども4人全員表示する仕様に比べて特段優れているとは思わないなー。実装は楽だけど（大事なことなので2回言いました

**Comment by edochan** [comment]
>内部的には嫁の数に上限は置かないけど、表示の都合で4人までにするのが適切かなぁと感じている

失礼見落としてました(；´Д｀)

**Comment by ponkotuy** [comment]
今考えている仕様

* 嫁にできるのは4人まで
* 内部的には序列付き（1から4ですね）
* ユーザのトップページに最大6人表示される
* 嫁設定ボタンをポチると序列の最後に追加（4人設定済なら4人目が消されて入れ替わり
* 嫁削除ボタンを本人のみ表示。削除したら序列の繰り上げ

**Comment by ponkotuy** [comment]
割とUIまわりの変更最小でできそう

**Comment by b-wind** [comment]
利用者のブラウザで６人並べられるんですかねぇ。

**Comment by ponkotuy** [comment]
現行仕様だと992px以上のウィンドウサイズだと3人、それ以下だと2人並ぶようになってるから、それを2〜3段で表示するようになる

**Comment by ponkotuy** [comment]
1200px以上のユーザは4人表示する仕様への変更も考えてはいる

**Comment by ponkotuy** [comment]
言い忘れてた、スマホは1段1人です

**Comment by b-wind** [comment]
特に異論があるわけでも無いけれど、見た目的にどうなるのかなという疑問は少し。
今の感じだと下に提督経験値グラフが並ぶ程度だし問題無いか。

**Comment by ponkotuy** [comment]
似たようなのは既に艦隊のmodalであってな http://myfleet.moe/user/10007732/ship#modal=true&id=4&fleet=true まぁ気になるならできた後にPR出してよw

**Comment by ponkotuy** [comment]
DB見たらUserSettingsに紐づけてたので結構書き換えないといけないかも

**Comment by ponkotuy** [comment]
実装多いかと思ってbranch作ってみた https://github.com/ponkotuy/MyFleetGirls/tree/yomes

**Comment by ponkotuy** [comment]
DB側は対応したのであとはdeleteボタン作るだけかな

**Comment by ponkotuy** [comment]
deleteボタンでけたけど、なんかUIびみょいし一旦整理する必要があるかな…

**Comment by ponkotuy** [comment]
https://github.com/ponkotuy/MyFleetGirls/pull/104
