### ISSUE TITLE
一時ファイルが作成されたままになる

### ISSUE THREAD

**Issue by ttdoda** [ponkotuy/MyFleetGirls#98]
クライアントを長期間起動していると、/tmpや%LOCALAPPDATA%\tempにtempfiletool_myfleet～ というファイルが大量に作成されている。

必要が無くなった時点で削除するか、適当なタイミング(起動時等)に一括で削除するようにして欲しい。

**Comment by ponkotuy** [comment]
んーちゃんとcloseしてない案件かな。調査します

**Comment by ponkotuy** [comment]
closeしてなかったのは合ってたけど、割かし根が深かった。Javaのtempファイルの扱い結構難しい https://github.com/ponkotuy/MyFleetGirls/commit/f3c90d0c1c1af0c0d4547492930bf09661c6a50f

**Comment by ponkotuy** [comment]
クライアント変更込みなので次期リリースに入れる
